---
title: "Validity"
linktitle: "Week 6: Validity"
output:
  rmarkdown::html_document:
    toc: true
menu:
  due:
    parent: 'To Do List'
    weight: 6
type: docs
weight: 1
---

`r blogdown::shortcode("r-walkthrough-header")`

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r eval = TRUE, echo = FALSE}

wk_post <- 
  
  tibble(

Description = c("Read <i>Aural Versus Visual Design of Questions and Questionnaires</i> in Dillman, Smyth, &amp; Christian (2014)",
                "Read <i>Ordering Questions and Testing for Question Order Effects</i> in Dillman, Smyth, &amp; Christian (2014)",
                "Read <i>Test Development</i> in Albano (2020)",
                "Read <i>Validity</i> in Albano (2020)",
                "Complete the module <span style='color:#ffc787;font-weight:bold'><i>Joining Data with dplyr</i></span>",
                "Go through the slideshow <span style='color:#6ac4cd;font-weight:bold'>Factorial Validity</span> prior to the Factor Analysis walkthrough",
                "Go through a walkthrough on how to conduct and interpret a factor analysis",
                "Complete and submit the associated <i class='fa-brands fa-r-project'></i> task for the module",
                "Submit <span style='color:#6acda5;font-weight:bold'>Refine the Draft</span> after recieving feedback on your second deliverable",
                "If you like the idea of learning by visualizing the steps in a pipe, then consider using <b>Tidy Data Tutor</b>"
                ),


Details = c("<a href='/readings/06-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/06-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/06-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/06-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/modules/06-module/#data-camp'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/tasks/06-task/#factorial-validity'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/walkthroughs/06-walkthrough/#factor-analysis'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
              "<a href='/modules/06-module/#r-task'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/deliverables/03-l3/'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/tasks/06-task/#factorial-validity'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>"
            ),

Icon = c("library",
         "library",
         "offsite",
         "offsite",
         "dc",
         "slideshow",
         "walkthrough",
         "ecampus",
         "ecampus",
         "offsite"),

Site = c("https://ebookcentral.proquest.com/lib/wvu/reader.action?docID=1762797&ppg=189",
         "https://ebookcentral.proquest.com/lib/wvu/reader.action?docID=1762797&ppg=248",
         "https://www.thetaminusb.com/intro-measurement-r/development.html",
         "https://www.thetaminusb.com/intro-measurement-r/validity.html",
         "https://www.datacamp.com",
         "",
         "",
         "https://ecampus.wvu.edu",
         "https://ecampus.wvu.edu",
         "https://tidydatatutor.com/"
         )
)
```

<center>
`r knitr::spin_child(here::here("content", "post_frame.R"))`
</center>
