---
title: "Detailing Studies"
linktitle: "Week 8: Detailing Studies"
output:
  rmarkdown::html_document:
    toc: true
menu:
  due:
    parent: 'To Do List'
    weight: 8
type: docs
weight: 1
---

`r blogdown::shortcode("aes-header")`

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}

wk_post <- 
  
  tibble(

Description = c("Read <i>A Checklist of Mixed Methods Elements in a Submission for Advancing the Methodology of Mixed Methods Research</i> in Fetters, M.D. & Molina-Azorin, J.F. (2019a)",
                "Read <i>The Journal of Mixed Methods Research Starts a New Decade: Principles for Bringing in the New and Divesting of the Old Language of the Field</i> in Fetters, M.D. & Molina-Azorin, J.F. (2017)",
                "Read <i>New Requirements to Include the Methodological Contribution in Articles Published in the Journal of Mixed Methods Research</i> in Fetters, M.D. & Molina-Azorin, J.F. (2019b)",
                "Read <i>Publishing a Methodological Mixed Methods Research Article</i> in Fetters, M.D. & Freshwater, D. (2015)",
                "Begin the module <span style='color:#ffc787;font-weight:bold'><i>Introduction to Text Analysis in R</i></span>",
                "Begin the associated <i class='fa-brands fa-r-project'></i> task for the module",
                "Carefully go through chapters 3 and 4 in <i>Text Mining with R: A Tidy Approach</i>",
                "Review the slideshow <span style='color:#bff4ee;font-weight:bold'>Sentiment Analysis</span> after class",
                "Submit your fourth deliverable <span style='color:#6acda5;font-weight:bold'>Update the Draft</span>",
                "Begin work on your fifth deliverable <span style='color:#6acda5;font-weight:bold'>Refine the Draft</span> after recieving feedback on the prior submission"
                ),


Details = c("<a href='/readings/08-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/08-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/08-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/readings/08-readings/#read-some-text'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/modules/08-module/#data-camp'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/modules/08-module/#r-task'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/walkthroughs/08-walkthrough/#tidy-text-mining'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/tasks/08-task/#inclassnotes'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
            "<a href='/deliverables/04-l4/'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
             "<a href='/deliverables/05-l5/'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>"
            ),

Icon = c("pdf",
         "pdf",
         "pdf",
         "pdf",
         "dc",
         "R",
         "offsite",
         "slideshow",
         "ecampus",
         "ecampus"),

Site = c("/readings/08-readings/#download-literature",
         "/readings/08-readings/#download-literature",
         "/readings/08-readings/#download-literature",
         "/readings/08-readings/#download-literature",
         "https://www.datacamp.com",
         "",
         "https://www.tidytextmining.com",
         "",
         "https://ecampus.wvu.edu/",
         "https://ecampus.wvu.edu/")
)
```

<center>
`r knitr::spin_child(here::here("content", "post_frame.R"))`
</center>
