---
title: "Regression and Correlation & Analysis of Variance"
linktitle: "Week 13: Regression and Correlation & Analysis of Variance"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  due:
    parent: "To Do"
    weight: 13
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(tidyverse)
library(fontawesome)
library(knitr)
library(kableExtra)
```

`r blogdown::shortcode("aes-header")`

### What to do for Week 13 after class ends

```{r eval = TRUE, echo = FALSE}
unchecked <- as.character(fontawesome::fa("square", fill = "#4682b4"))

checked <- as.character(fontawesome::fa("square-check", fill = "#4682b4"))

wk_post <- tibble(
  
Submit = c(unchecked,
           checked,
           checked,
           unchecked,
           checked,
           checked,
           checked,
           unchecked,
           unchecked),

Description = c("Review the solution set from the Chapter 10 homework set",
                "Complete problems 1, 2, 6 in Chapter 11",
                "Complete <b><i>optional</i></b> problems 1, 2 in Chapter 12",
                "Take a look at a compilation of statistical commands in R",
                "Finish the first <b><i>optional</i></b> extra credit module <i>Analyzing Survey Data in R</i>",
                "Finish the second <b><i>optional</i></b> extra credit module <i>Fundamentals of Bayesian Data Analysis in R</i>",
                "Finish the third <b><i>optional</i></b> extra credit module <i>Reporting with R Markdown</i>",
                "Watch videos on the Regression & Correlation and ANOVAs",
                "Watch a fantastic explanation on a concept called <i>Regression to the Mean</i>"),


Location = c("[Link](/tasks/12-tasks/#solutions)",
             "[Link](/tasks/13-tasks/#homework)",
             "[Link](/tasks/13-tasks/#homework)",
             "[Link](/materials/13-content/#r-walkthroughs)",
             "[Link](/datacamp/07-module/)",
             "[Link](/datacamp/08-module/)",
             "[Link](/datacamp/09-module/)",
             "[Link](/materials/13-example/#crash-course-statistics)",
             "[Link](/extras/13-example/#veritasium)"
             )
) %>%
  mutate(Link = paste0("<a href=", str_extract_all(Location, "(?<=\\().+?(?=\\))"), "> <i class='fa-solid fa-link' style='color:#598fff'></i> </a>")) %>%
  select(-Location)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_post, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE)  %>%
  column_spec(1, width = "10em") %>%
  row_spec(0:nrow(wk_post), extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```

<br />

### What to do for Week 14 before coming to class

```{r eval = TRUE, echo = FALSE}
book <- as.character(fontawesome::fa("book", fill = "#739670"))

chalkboard <- as.character(fontawesome::fa("chalkboard", fill = "#764874"))

lightbulb <- as.character(fontawesome::fa("lightbulb", fill = "#eb7b59"))

wk_pre <- tibble(
  
Area = c(book, 
         chalkboard,
         lightbulb),

Description = c("Study for your second exam!",
                "If you like stats in R but hate the fact that there's not enough clicking, check out the software Jamovi",
                "Take a look at at an introduction to Bayesian Statistics"),

Location = c("[Link](/tasks/02-exam/)",
             "[Link](https://www.jamovi.org/){target='_blank'}",
             "[Link](/extras/14-example)")

) %>%
  mutate(Link = paste0("<a href=", str_extract_all(Location, "(?<=\\().+?(?=\\))"), "> <i class='fa-solid fa-link' style='color:#ff598f'></i> </a>")) %>%
  select(-Location)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_pre, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em") %>%
  row_spec(0:nrow(wk_pre), extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```  
