---
title: "Deadline"
linktitle: "Week 15: Deadline"
output:
  rmarkdown::html_document
menu:
  due:
    parent: "To Do List"
    weight: 15
type: docs
weight: 2
---

`r blogdown::shortcode("aes-header")`

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r eval = TRUE, echo = FALSE}

wk_post <- 
  
  tibble(
    
    Description = c("Review the criteria needed for the <span style='color:#52bf90; font-weight:bold;'>Final Report</span> due at the <i><b>end of this week</b></i>",
                    "Preview the criteria needed for the <span style='color:#52bf90; font-weight:bold;'>Presentation of Results</span> due at the <i><b>end of week 16</b></i>"
    ),
    
    
    Details = c("<a href='/deliverables/04-final-report/'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>",
                "<a href='/deliverables/05-presentation-of-results/'><span style='font-size: 25px; color: #89cff0;'><i class='fas fa-info-circle'></i></span></a>"
                ),
    
    Icon = c("ecampus",
             "ecampus"),
    
    Site = c("https://ecampus.wvu.edu",
             "https://ecampus.wvu.edu")
  )
```

<center>
`r knitr::spin_child(here::here("content", "post_frame.R"))`
</center>
