[build]
  command = "hugo --gc --minify"
#  base    = "exampleSite"
  publish = "public"

[build.environment]
  HUGO_THEME = "hugo-academic"
  HUGO_VERSION = "0.74.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

  [context.branch-deploy]
    command = "echo branch"

  [context.branch-deploy.environment]
    NODE_ENV = "development"

  [context.staging] # 'staging' is a branch name
    command = "echo 'staging'"
    base = "staging"

  [context."feat/branch"]
    command = "echo 'special branch'"
    base = "branch"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.74.3" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
    HUGO_VERSION = "0.74.3"
