---
title: Visualization
menu:
  resource:
    parent: Resources
type: docs
weight: 10
output:
  blogdown::html_page:
      toc: TRUE
---

## Interesting and excellent real world examples
- [Australia as 100 people](https://flowingdata.com/2017/06/28/australia-as-100-people/){target="_blank"}: You can make something like this with [d3](https://d3js.org/){target="_blank"} and the [potato project](https://github.com/civisanalytics/potato){target="_blank"}.
- [Marrying Later, Staying Single Longer](https://flowingdata.com/2017/07/17/marrying-age-over-the-past-century/){target="_blank"}
- [The Stories Behind a Line](http://www.storiesbehindaline.com/){target="_blank"}

## How to select the appropriate chart type

Many people have created many useful tools for selecting the correct chart type for a given dataset or question. Here are some of the best:

- [**The Chartmaker Directory**](http://chartmaker.visualisingdata.com/){target="_blank"}: Examples of how to create 51 different types of visualizations in 31 different software packages, including Excel, Tableau, and R.
- [**Emery's Essentials**](http://annkemery.com/essentials/){target="_blank"}: Descriptions and examples of 26 different chart types.
- [**From Data to Viz**](https://www.data-to-viz.com/){target="_blank"}: A decision tree for dozens of chart types with links to R and Python code.
- [**The Data Visualisation Catalogue**](http://www.datavizcatalogue.com/){target="_blank"}: Descriptions, explanations, examples, and tools for creating 60 different types of visualizations.
- [**The Data Viz Project**](http://datavizproject.com/){target="_blank"}: Descriptions and examples for 150 different types of visualizations. Also allows you to search by data shape and chart function (comparison, correlation, distribution, geographical, part to whole, trend over time, etc.).
- [**R Graph Catalog**](http://shinyapps.stat.ubc.ca/r-graph-catalog/){target="_blank"}: R code for 124 ggplot graphs.


## General resources

- [**Ann K. Emery's blog**](http://annkemery.com/blog/){target="_blank"}: Blog and tutorials by [Ann Emery](https://twitter.com/AnnKEmery){target="_blank"}.
- [**Data Literacy Starter Kit**](https://docs.google.com/document/d/1kKRadOiF0LruItsvGA40fSDZkAQfCqC_Ela0gBdo8A4/edit){target="_blank"}: Compilation of resources to become data literate by [Laura Calloway](http://lauracalloway.com/){target="_blank"}.
- [**The Data Visualization Checklist**](http://annkemery.com/checklist/){target="_blank"}: A helpful set of criteria for grading the effectiveness of a graphic.
- [**Evergreen Data**](http://stephanieevergreen.com/){target="_blank"}: Helpful resources by [Stephanie Evergreen](https://twitter.com/evergreendata).
- [**FlowingData**](https://flowingdata.com/){target="_blank"}: Blog by [Nathan Yau](https://twitter.com/flowingdata){target="_blank"}.
- [**Info We Trust**](http://infowetrust.com/){target="_blank"}: Detailed explorations of visualizations by [RJ Andrews](https://twitter.com/infowetrust){target="_blank"}, including a [beautiful visual history of the field](http://infowetrust.com/history/){target="_blank"}.
- [**Information is Beautiful**](http://www.informationisbeautiful.net/){target="_blank"}: Blog by [David McCandless](https://twitter.com/mccandelish){target="_blank"}.
- [**PolicyViz**](https://policyviz.com/): Regular podcast and site full of helpful resources by [Jon Schwabisch](https://twitter.com/jschwabish){target="_blank"}.
- [**Visualising Data**](http://www.visualisingdata.com/){target="_blank"}: Fantastic collection of visualization resources, articles, and tutorials by [Andy Kirk](https://twitter.com/visualisingdata){target="_blank"}.
- [**Storytelling with Data**](http://www.storytellingwithdata.com/): Blog and site full of resources by Cole Nussbaumer Knaflic.
- [**Junk Charts**](http://junkcharts.typepad.com/){target="_blank"}: Blog by [Kaiser Fung](https://twitter.com/junkcharts){target="_blank"}.
- [**WTF Visualizations**](http://viz.wtf/){target="_blank"}: Visualizations that make you ask "wtf?"
- [**R Psychologist**](https://rpsychologist.com/viz/){target="_blank"}: A fantastic collection of interactive applications of statistical concepts by [Kristoffer Magnusson](https://twitter.com/krstoffr){target="_blank"}
- [**Seeing Data**](http://seeingdata.org/){target="_blank"}: A series of research projects about perceptions and visualizations.


## Visualization in Excel

- [**How to Build Data Visualizations in Excel**](http://stephanieevergreen.com/how-to/){target="_blank"}: Detailed tutorials for creating 14 different visualizations in Excel.
- [**Ann Emery's tutorials**](http://annkemery.com/category/visualizing-data/tutorials/){target="_blank"}: Fantastic series of tutorials for creating charts in Excel.


## Visualization in Tableau

Because it is focused entirely on visualization and a well-supported commercial product, Tableau has a [phenomenal library of tutorials and training videos](https://www.tableau.com/learn/training){target="_blank"}. There's [a helpful collections of videos here](https://www.quora.com/What-are-some-good-video-tutorials-for-learning-Tableau){target="_blank"}, as well.
