---
title: "Recent Talks"
weight: 6
---

```{r, echo=FALSE, message=FALSE}
source("initlib.R")
```

```{r echo=FALSE, eval=TRUE, warning=FALSE}
tibble(
  
  ws = c("Who?",
         "What?",
         "Where?",
         "When?",
         "Why?"),
  
  description = 
    c("<a href='https://counselingandlearningsci.wvu.edu/faculty-staff/reagan-curtis'>Dr. Reagan Curtis</a>, Cari, and I",
      "<a href='https://www.aera.net/Events-Meetings/Annual-Meeting'>2022 AERA Annual Meeting</a>",
     "San Diego, CA",
     "Fri, April 22, 11:30am to 1:00pm PDT @ Manchester Grand Hyatt",
     "To present our paper <a href='https://tinyurl.com/yye55wrz'>Best of Both Worlds: Affordances of Mixing Machine Learning and Qualitative Content Analysis</a>")
  
) %>% 
  kable(col.names = c("", ""),
        escape = FALSE,
        html = TRUE,
        align = 'll') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "5em", color = "#ffffff", extra_css = 'vertical-align: middle !important;', border_left = "2px #1e1e1e") %>%
  column_spec(2, width = "20em", color = "#ffffff", extra_css = 'vertical-align: middle !important;') %>%
  row_spec(0:5, background = "#1e1e1e")
```
</center>
