---
title: "Aims, Scope and Sequencing"
linktitle: "Week 3: Aims, Scope and Sequencing"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

## Evaluation Phase
We are currently in the pre-evaluation phase. This involves

```{r echo = FALSE}

unchecked <- as.character(fontawesome::fa("circle", fill = "#e4e4e4", height = "15px"))

checked <- as.character(fontawesome::fa("check-circle", fill = "#428bca", height = "15px"))

pre <- tibble(
  
  phase = c("Pre-Evaluation",
            "",
            ""),
  
  task = c("Gathering a team",
           "Thinking about potential programs",
           "Submitting a prospectus"),
  
  current <- c(checked,
               unchecked,
               unchecked)
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
  pre %>%
  kbl(escape = FALSE,
      align = 'llc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "20em") %>% 
  row_spec(2, extra_css = 'vertical-align: middle !important;') 
```
</center>
