---
title: "Causation and Criteria"
linktitle: "Week 4: Causation and Criteria"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 4
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

## Evaluation Phase
We are currently in the pre-evaluation phase. This involves

```{r echo = FALSE}

unchecked <- as.character(fontawesome::fa("circle", fill = "#e4e4e4", height = "15px"))

checked <- as.character(fontawesome::fa("check-circle", fill = "#428bca", height = "15px"))

pre <- tibble(
  
  phase = c("Pre-Evaluation",
            "",
            ""),
  
  task = c("Gathering a team",
           "Thinking about potential programs",
           "Submitting a prospectus"),
  
  current <- c(unchecked,
               checked,
               unchecked)
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
  pre %>%
  kbl(escape = FALSE,
      align = 'llc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "20em") %>% 
  row_spec(2, extra_css = 'vertical-align: middle !important;') 
```
</center>

## Causal Models in Evaluation

Take a look at the following resources below

1. the UNICEF guide [Overview: Strategies for Causal Attribution](https://web.archive.org/web/20150424163020/http://devinfolive.info/impact_evaluation/img/downloads/Overview_Strategies_for_Causal_Attribution_ENG.pdf){target="_blank"}, and 

2. its corresponding video 

<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/4lv3DJFBLqI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>

taken from Jane Davidson's <span style = "color:#C9373B">Better</span><span style = "color:#593A90">Evaluation</span> page [Overview: Strategies for Causal Attribution](https://www.betterevaluation.org/en/resources/guide/overview_strategies%20_for_causal%20_attribution){target="_blank"}.