---
title: "Ordering Questions and Testing for Question Order Effects"
linktitle: "Week 7: Ordering Questions and Testing for Question Order Effects"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

### Visual Clues

#### Synopsis
Item development for any instrument is not an easy task. Furthermore you rarely have the chance of amending a question on surveys in particular after distribution so they require that items be *perfect*. While pilot testing certainly helps with this process, using certain formatting techniques can yield gains in responses. 

#### What you need^[You may have to right click and download it depending on your browser settings.]
Please download the following files and save them in a single folder

- [likert_colorpalettes_functions.R](/exscripts/likert_colorpalettes_functions.R) script.
- [likert_colorpalettes.R](/exscripts/likert_colorpalettes.R) script.
- [text_box_size](/snippets/text_box_size.txt) text file.
- [vertical_mc_spacing](/snippets/vertical_mc_spacing.txt) text file.

#### Walkthrough: Part I - Spacing
<center>
<iframe class="smart-player-embed-container-iframe" id="embeddedSmartPlayerInstance" src="/videos/Element_spacing/media/index_player.html?embedIFrameId=embeddedSmartPlayerInstance" width="640" height="360" frameborder="0" scrolling="no"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</center>

#### Walkthrough: Part II - Colors
<center>
<iframe class="smart-player-embed-container-iframe" id="embeddedSmartPlayerInstance" src="/videos/Element_colors/media/index_player.html?embedIFrameId=embeddedSmartPlayerInstance" width="640" height="360" frameborder="0" scrolling="no"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</center>

#### Links

- [Color Hex](https://www.color-hex.com/){target="_blank"}
- [uiGradients](https://uigradients.com/){target="_blank"}
- [EDP 693 Resources page for Design](/resource/design/){target="_blank"}




