---
title: "Estimations"
linktitle: "Week 9: Estimations"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Examples
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---
```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### Crash Course Statistics
This week we have another brief introduction from Crash Course Statistics on **Confidence Intervals** and a great introduction to the *p*-value.

<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/yDEvXB6ApWc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>
<br>
<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/bf3egy7TQ2Q" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</p>

Remember you can always access a Crash Course Statistics playlist using the following  [link](https://www.youtube.com/playlist?list=PL8dPuuaLjXtNM_Y-bUAhblSAdWRnmBUcr){target="_blank"}.

### Power and Significance 

If you like interactive things and want to see how Type I & Type II errors, $\alpha$, $\beta$, *p*-values, power and effect sizes all play together, try Kristoffer Magnusson's wonderful page [Understanding Statistical Power and Significance Testing: an interactive visualization](https://rpsychologist.com/d3/nhst/){target="_blank"}.

### Election Season and Statistics

If you want to see inferential statistics in action, give a look at [FiveThirtyEight 2020](https://projects.fivethirtyeight.com/2020-election-forecast/){target="_blank"} where researchers use polling and regional data to forecast the upcoming elections.