---
title: "About the Examples"
menu:
  example:
    parent: Overview
    weight: 1
type: docs
weight: 1
---

This section contains extra material to supplement what is covered that week. Sometimes this is just a few links for you to look at and other times its fully annotated R code that you can use as a reference for helping you along with a task. Please access the material on this site this section after you have finished the reading(s). 

From time to time, it may also contains video of coding some examples pieces so you can see what it looks like to work with R in real time. You'll definitely notice that I make all sorts of errors, which *is absolutely normal* and happens to everyone!

### Need Help?
I always prefer a face to face meeting if possible but since that's not possible, you can schedule a Zoom via the [Calendar](https://calendly.com/nopiecharts/short30){target="_blank"} or contact me within [Slack](http:/2021edp693e.slack.com){target="_blank"} by tagging my name `@Dr. Abhik Roy` in a text box along with your message.
