---
title: "Base R is a Thing"
linktitle: "Week 2: Base R is a Thing"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Readings
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

<style>
.hvr-sweep-to-left {
  display: inline-block;
  vertical-align: middle;
  -webkit-transform: perspective(1px) translateZ(0);
  transform: perspective(1px) translateZ(0);
  box-shadow: 0 0 1px rgba(0, 0, 0, 0);
  position: relative;
  -webkit-transition-property: color;
  transition-property: color;
  -webkit-transition-duration: 0.25s;
  transition-duration: 0.25s;
}

.hvr-sweep-to-left:before {
  content: "";
  position: absolute;
  z-index: -1;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: #175676;
  -webkit-transform: scaleX(0);
  transform: scaleX(0);
  -webkit-transform-origin: 100% 50%;
  transform-origin: 100% 50%;
  -webkit-transition-property: transform;
  transition-property: transform;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-timing-function: ease-out;
  transition-timing-function: ease-out;
}

.hvr-sweep-to-left:hover, .hvr-sweep-to-left:focus, .hvr-sweep-to-left:active {
  color: white;
}

.hvr-sweep-to-left:hover:before, .hvr-sweep-to-left:focus:before, .hvr-sweep-to-left:active:before {
  -webkit-transform: scaleX(1);
  transform: scaleX(1);
}
</style>


### Read Things
We'll be transitioning out of Base R to the Tidyverse. To get an idea of what that looks like by reading a couple of articles from Hadley Wickham:

1. Wickham, H. (2010). A Layered Grammar of Graphics. *Journal of
Computational and Graphical Statistics 19*(1), 3-28. [https://doi.org/10.1198/jcgs.2009.07098](https://doi.org/10.1198/jcgs.2009.07098){target="_blank"}
2. Wickham, H. (2013). Graphical Criticism: Some Historical Notes, *Journal of Computational and Graphical Statistics, 22*(1), 38-44. [https://doi.org/ 10.1080/10618600.2012.761140](https://doi.org/ 10.1080/10618600.2012.761140){target="_blank"}

```{r echo=FALSE,eval=TRUE}
downloadthis::download_file(
  path = here::here("static", "readings", "EDP693eWeek2Readings.zip"),
  output_name = "Week 1 Readings",
  button_label = "Download the Readings",
  button_type = "default",
  has_icon = TRUE,
  icon = "fa fa-save",
  class = "hvr-sweep-to-left"
  )
```

