---
title: "The Normal Distribution"
linktitle: "Week 5: The Normal Distribution"
menu:
  readings:
    parent: Readings
    weight: 5
type: docs
weight: 1
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(fontawesome)
```

<style>
table > tbody > tr:hover > td, table > tbody > tr:hover > th {
  background-color: #ffffff;
}
</style>

```{r eval = TRUE, echo = FALSE, message=FALSE}

read_schedule <- read_csv("read.csv",
                          show_col_types = FALSE) %>% 
                  as_tibble() %>%
                  mutate(Required = case_when(
                  Required == "checked" ~ as.character(fontawesome::fa("circle-check", fill = "#428bca", height = "15px")),
                Required == "unchecked" ~ as.character(fontawesome::fa("circle-xmark", fill = "#d9534f", height = "15px"))
              )) %>%
                  mutate(across(everything(), as.character)) %>%
                    filter(Group == 5) %>% #CHANGE HERE
                    select(-Group, -Details) %>%
                  filter_all(any_vars(!is.na(.))) %>% 
                  mutate(
                    across(everything(), ~replace_na(.x, ""))
                  ) %>%
                select_if(~!all(is.na(.))) %>%
  mutate(Title = paste0("<b>", Title, "</b>"))
  
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(read_schedule, 
      escape = FALSE,
      align = 'cllccccc') %>%
  kable_styling(full_width = FALSE,
                bootstrap_options = c("striped", "hover")) %>%
  column_spec(1, width = "5em") %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "12em") %>%
  column_spec(4, width = "5em") %>%
  column_spec(5, width = "10em") %>%
  column_spec(6, width = "10em") %>%
  column_spec(7, width = "10em") %>%
  row_spec(0:1, extra_css = 'vertical-align: middle !important;', background = "#ffffff")
```
