---
title: "The Importance of Knowing What's Important"
linktitle: "Week 6: The Importance of Knowing What's Important"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  readings:
    parent: Readings
    weight: 6
type: docs
weight: 1
---

`r blogdown::shortcode("aes-header")`

```{r load_packages, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(fontawesome)
library(knitr)
library(kableExtra)
library(here)
```

## Respond to Posts

Please create **two responses** for each of the posts below on 

- <a href='https://2022edp617.slack.com/archives/C0322TGRW8N' target='_blank' style='color: #ff8384;'><font size='4px'>#evaluation-politicization</font></a>

- <a href='https://2022edp617.slack.com/archives/C0326L34HJ9' target='_blank' style='color: #ff8384;'><font size='4px'>#which-values</font></a>

## Read the Book

Please read and address the following questions using a single post

```{r echo=FALSE}

readings <- tibble(
  
  title <- c('<i>Determining Importance</i>',
             '<i>The Merit Determination Step</i>'
  ),
  
  chapter <- c(
    "7",
    "8"
  ),
  
  arrow = c("external",
            "external"),
  
  link = c(
    "https://methods-sagepub-com.wvu.idm.oclc.org/book/evaluation-methodology-basics/n7.xml",
    "https://methods-sagepub-com.wvu.idm.oclc.org/book/evaluation-methodology-basics/n8.xml"),
  
  question <- c(
    "How will or did you infer the important criteria from the stakeholder/sponsor interview?",
    "Recall that you as the evaluator are the expert <i>but</i> a sponsor is the person who hires and pays you. Given this, what would you do in a situation where you and the sponsor fundamentally disagree with <i>what should be evaluated</i>?"
  ),
  
   area = c("`#important-criteria`{=markdown}",
            "`#merit-disagreement`{=markdown}"),
  
  post = c(
    "https://2022edp617.slack.com/archives/C032T8GK5EZ,
    https://2022edp617.slack.com/archives/C032FH7QLRM"
  ),

  
  .name_repair = "minimal"
  
)

```

<center>
```{r, echo=FALSE}
readings %>%
  mutate(arrow = case_when(
    str_detect(`arrow`, "external") ~ '<div style="font-size: 0.5rem;"><i class="fa fa-external-link fa-2x" aria-hidden="true" style="color:#559977"></i></div>',
    TRUE ~ NA_character_
    )
  ) %>%
  mutate(link = na_if(link, "")) %>%
  mutate(link = case_when(
    !is.na(arrow) ~ paste0("<a href=",link," target='_blank'>",arrow,"</a>"),
    TRUE ~ NA_character_
    )
  ) %>%
  mutate(post = case_when(
    !is.na(area) ~ paste0("<a href=",post," target='_blank' style='color: #ff8384;'><font size='4px'>",area,"</font></a>"),
    TRUE ~ NA_character_
    )
  )  %>%
  select(-arrow, -area) %>% 
  mutate_all(replace_na,"") %>%
  kbl(col.names = c("Title", "Chapter", "Link", "Question", "Post"), 
      "html", 
      escape = FALSE,
      align = 'lcclc') %>%
  kable_paper(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "5em") %>%
  column_spec(3, width = "5em") %>% 
  column_spec(4, width = "30em") %>% 
  column_spec(5, width = "10em") %>% 
  row_spec(0:2, extra_css = 'vertical-align: middle !important;', color = "#ffffff", background = "transparent") 
```
</center>
