---
title: "About the Readings"
menu:
  readings:
    parent: Overview
    weight: 1
type: docs
weight: 1
---

## The Course Text
Each class session has a set of required readings that you should complete ***before*** doing anything else. It also allows you to ask questions prior to moving on! With that said, think of the text as a reference, in that

- it contains a lot of information that you may use but probably not right now, and
- it gives you a basis to ask intelligent questions. 

So you should absolutely read it to get a basis but in the long run, you will learn more from this course by doing.

## The Course Nontext
There's no such thing as visual learner or any other kind of learner [(Rogowsky, Calhoun & Tallal, 2015)](https://www.apa.org/pubs/journals/features/edu-a0037478.pdf){target="_blank"}. With that said, reinforcement using different mediums such as presentations, videos, visualizations, walkthroughs, etc helps. These however take a lot of time to construct so please take some time to go through them. Is the production quality Hollywood? No because I'm a professor at a public university who doesn't sound like Morgan Freeman, have three children and drive a car with duct tape on it BUT they'll be decent. I am always open to suggestions so if you have any, please send them along!
<br>
<br>
*Pictures are better than words because some words are big and hard to understand.* 
<br> 
- Peter Griffin

### Need Help?
I always prefer a face to face meeting if possible but since that's not possible, you can schedule a Zoom via the [Calendar](https://calendly.com/nopiecharts){target="_blank"} or contact me within [Slack](https://2021edp613.slack.com){target="_blank"} by tagging my name `@Dr. Abhik Roy` in a text box along with your message.
