library(tidyverse)
library(knitr, warn.conflicts=FALSE)
library(kableExtra, warn.conflicts=FALSE)
library(here, warn.conflicts=FALSE)
library(fontawesome, warn.conflicts=FALSE)
library(downloadthis, warn.conflicts=FALSE)
library(showtext, warn.conflicts=FALSE)
font_add_google("Roboto Condensed", "roboto")
showtext_auto()
