---
title: "Introduction to the Tidyverse"
linktitle: "Introduction to the Tidyverse"
menu:
  datacamp:
    parent: Modules
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
library(tidyverse)
library(fontawesome)
```

<style>
table > tbody > tr:hover > td, table > tbody > tr:hover > th {
  background-color: #ffffff;
}
</style>

```{r eval = TRUE, echo = FALSE, message=FALSE}
dc_schedule <-  
  read_csv("dc.csv",
           show_col_types = FALSE) %>%
  as_tibble() %>%
                mutate(Required = case_when(
                Required == "checked" ~ as.character(fontawesome::fa("circle-check", fill = "#428bca", height = "15px")),
                Required == "unchecked" ~ as.character(fontawesome::fa("circle-xmark", fill = "#d9534f", height = "15px"))
              )) %>%
            mutate(across(everything(), as.character)) %>%
              filter(Group == 2) %>% #CHANGE HERE
              select(-Group, -`Due by_short`, -Course) %>%
              rename(`Due by` = `Due by_long`) %>%
              rename(Chapters = Chapters_long)  %>%
            filter_all(any_vars(!is.na(.))) %>% 
            mutate(
              across(everything(), ~replace_na(.x, ""))
            ) %>%
  select_if(~!all(is.na(.))) 
  
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(dc_schedule, 
      escape = FALSE,
      align = 'cccclc') %>%
  kable_styling(full_width = FALSE,
                bootstrap_options = c("striped", "hover")) %>%
  column_spec(1, width = "5em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "10em") %>%
  column_spec(4, width = "10em") %>%
  column_spec(5, width = "10em") %>%
  row_spec(0:5, extra_css = 'vertical-align: middle !important;', background = "#ffffff")
```