---
title: "About the Walkthroughs"
menu:
  walkthroughs:
    parent: Overview
    weight: 1
type: docs
weight: 1
---

### First Timers Note
This section contains extra material to help you understand a concepts covered for that week. Sometimes this is just a few links for you to look at and other times its annotated R code that you can use as a reference for helping you along with a task. Please access the material on this site this section after you have finished the reading(s). '

### In App Help

First things first, once a package has been loaded, you can use a `?` in front of any command to get more information about it. Sometimes the descriptions and/or examples aren't very helpful, but most of the time you should be able to find the information you are looking for. 

### What's This All About?

Barring the first week, every other example provided  is essentially a walkthrough. You may notice that all of the outputs are already done for you. The purpose of you going through the modules in Data Camp is to familiarize yourself of the structure and syntax.

### Need Help?
I always prefer a face to face meeting if possible but since that's not possible, you can schedule a Zoom via the [Calendar](https://calendly.com/nopiecharts/short30){target="_blank"} or contact me within [Slack](http:/2021edp611.slack.com){target="_blank"} by tagging my name `@Dr. Abhik Roy` in a text box along with your message.
