---
title: "Schedule"
slug: schedule
output:
  blogdown::html_page:
    toc: false
---

`r blogdown::shortcode("aes-header")`

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

## Legend

```{r icontibble, echo=FALSE, message=FALSE}
famod <- as.character(fa("cubes", fill = "#6fd8d3", height = "17px"))
faread <-  as.character(fa("book", fill = "#74d86f", height = "17px"))
faresources <-  as.character(fa("laptop-code", fill = "#848fd3", height = "17px"))
fatasks <- as.character(fa("tasks", fill = "#d86f9e", height = "17px"))
fadue <- as.character(fa("folder-open", fill = "#ffa700", height = "17px"))
fawalk <- as.character(fa("map", fill = "#c0bfbb", height = "17px"))

tableofcontent <- tibble(
  
  type <- c("Modules",
            "Readings", 
            "Resources",
            "Tasks",
            "To Do",
            "Walkthroughs"),
  
  location <- c("<a href='/modules/'>Go</a>",
                "<a href='/readings/'>Go</a>",
                "<a href='/resources/'>Go</a>",
                "<a href='/tasks/'>Go</a>",
                "<a href='/due/'>Go</a>",
                "<a href='/walkthroughs/'>Go</a>"),
  
  icon <- c(famod,
            faread,
            faresources,
            fatasks,
            fadue,
            fawalk),
  
  descr <- c("DataCamp modules",
             "Weekly readings",
             "Curated list of R related resources",
             "Tasks and deliverables",
             "Submission information",
             "Custom walkthroughs focused on content"
             ),
  
  .name_repair = "minimal"

  ) 
```

<center>
```{r, echo=FALSE}
tableofcontent %>%
  kbl(col.names = NULL, 
      "html", 
      escape = FALSE,
      align = 'lccl') %>%
  column_spec(1, bold = TRUE)  %>% 
  row_spec(1:6, extra_css = 'vertical-align: middle !important;', color = "#f7f7f7", background = "transparent") 
```
</center>

<center>
<span style="font-size:17px"><i>Note: tasks are due by <b>Sunday at 11:59 PM</b> unless otherwise noted.</i></span>
</center>
<br>
<br>

<hr style"width:50%; margin-left:25% !important; margin-right:25% !important;" />

## Weekly Overview 

`r blogdown::shortcode("schedule")` 
<!-- .date and .title are #ffffff in schedule.html --> 
<br>

<hr style"width:50%; margin-left:25% !important; margin-right:25% !important;" />

### Need Help?

`r blogdown::shortcode("meetings")`
