---
title: Data
menu:
  resource:
    parent: Resources
type: docs
weight: 2
---

There are a ton of places to find data related to whatever you want. The ones below are some of the more larger repositories:

- [**Data World**](http://www.threesixtygiving.org/data/data-registry/){target="_blank"}: A plethora of open data sets to peruse. If you are a data fiend, consider collaborating to solve problems.

- [**Data is Plural newsletter**](https://tinyletter.com/data-is-plural){target="_blank"}: Jeremy Singer-Vine sends a weekly newsletter of the most interesting public datasets he's found. You should subscribe to it. [He also has an archive of all the datasets he's highlighted.](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0){target="_blank"}

- [**Google Dataset Search**](https://toolbox.google.com/datasetsearch){target="_blank"}: Google indexes thousands of public datasets; search for them here.

- [**Kaggle**](https://www.kaggle.com/datasets){target="_blank"}: Kaggle hosts machine learning competitions where people compete to create the fastest, most efficient, most predictive algorithms. A byproduct of these competitions is a host of fascinating datasets that are generally free and open to the public. 

- [**US City Open Data Census**](http://us-cities.survey.okfn.org/){target="_blank"}: More than 100 US cities have committed to sharing dozens of types of data, including data about crime, budgets, campaign finance, lobbying, transit, and zoning. This site from the [Sunlight Foundation](http://sunlightfoundation.com/) and [Code for America](http://www.codeforamerica.org//) collects this data and rates cities by how well they're doing.
