---
title: "L4: The First Draft"
linktitle: "L4: The First Draft"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  tasks:
    parent: Deliverables
    weight: 4
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

<style>
ul {
    margin-left: 1.5em
}

#center {

text-align: center;

}
</style>

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(tidyverse)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### <span style="color:#35d6ed">Submission</span>
<i>[eCampus](https://ecampus.wvu.edu)</i>

### <span style="color:#65ddef">Type</span>

<i>Individual Submission</i>. Each student in the course must write their own narrative and should treat this as an individual submission. 

### <span style="color:#7ae5f5">Description</span>

While the construction of a literature review is a fluid process without well-defined criteria, there are some elements that can be outlined and will serve those individuals who enjoy having a list or checklist of items the best. With that in mind, begin to construct your first literature review draft.

### <span style="color:#97ebf4">Structure</span>

This submission must be constructed using the following general components and should be uploaded to [eCampus](https://ecampus.wvu.edu/) following the formatting guidelines given in the main [tasks page](/tasks/#formatting)

Building on the feedback you reviewed on our narrative from L1 and your matrix of your 25 articles, you will construct a first draft of your literature review. To practice the formatting of APA 7th papers, please submit your outline using the following components:

1. A cover page
2. 750-1250 words for the narrative
3. A references page following APA 7 guidelines

<br>
<center>
<hr style="width:10%"> 
</center>


### <span style="color:#c9f6ff">Extra Help?</span>

If you are a procedure oriented type of person, consider using the process below.

1. Build a <b>hub</b>
    
    a. Briefly characterize your area of research and what particular problem or question at issue you will address.
    
    b. Choose at least 3 central studies that you can create clear and distinct connections - aka a <i>hub</i>. Note these may not be the central studies you end up with but they should serve as a good starting point.
    
    c. Summarize and synthesize the studies
    
2. Now do at least one of the following, though you will likely do both:
    
  + Build <b>authorities</b>. Repeat steps a-c with another set of seemingly independent studies to create another cluster of sources - aka an <i>authority</i>. Then attempt to find a logical connection between them. If none exists, keep that cluster elsewhere for possible use later. 
    
  + Build a <b>citation network</b>. Begin adding studies that appear to identify with at least one of your central studies and build out your narrative.
<!--
<br>
<br>
<hr style="width:30%;text-align:left;margin-left:0">


<font size="-1"><a id="1" href="#" onclick="history.back();"><sup>1</sup></a> Adapted from an <a href="http://clt.astate.edu/mhayes/exampleoutline.htm" target="_blank"> example</a> by Dr. Marceline Thompson-Hayes, Arkansas State University</a></font>
-->
