---
title: "Give an Elevator Pitch"
linktitle: "Give an Elevator Pitch"
menu:
  tasks:
    parent: Deliverables
    weight: 7
type: docs
weight: 7
editor_options: 
  chunk_output_type: console
---

`r blogdown::shortcode("aes-header")`

<style>
.article-style img, 
.article-style video {
  margin-left: 0;
  margin-right: auto;
  margin-top: 0rem;
  margin-bottom: 1rem;
  vertical-align: text-top;
  padding: 0;
  bottom: 0px;
  display: inline;
}

ul {
    margin-left: 1.5em
}

.dark h1 {
color:#6acda5
}

docs-sidebar .docs-toc-item.active a, 
.docs-sidebar .nav > .active:hover > a, 
.docs-sidebar .nav > .active > a {
  font-weight: bold;
  color: #6acda5;
  background-color: transparent;
}
</style>

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

Carefully read through the directions below 

1. *Elevator Pitch*
    + Create a 1 minute (+/- 10 seconds) [elevator pitch](https://uclalibrary.github.io/research-tips/deconstructing-the-elevator-speech/){target="_blank"} introducing yourself, describing the evaluation, research, or project, intended method/design, proposed analysis, and and its significance^[with the intent to garner interest in your study]. For more information, head over to the [Creating an Elevator Talk](/resources/elevatortalk/) on the Resources page. <b>Please note that there are no make-ups or late attempts accepted for this deliverable</b>
  
    + Audience members are expected to ask questions and/or provide constructive criticism during a two to three minute Q&A session
  
2. Please submit the *Elevator Pitch* to
    + <a href="https://edp618fall2022.slack.com/archives/C04CV0ANEB1" target="_blank" style='color:#ff8384;'> #elevator-pitch</a> in a single posting on Slack
  
    + <a href="https://ecampus.wvu.edu" target="_blank"> eCampus</a>
  
<br />

<center>
<p id="rounded_corners">
All submissions leading up to the proposal can be found on the main <a href="/tasks/#proposal">Tasks</a> page
<p>
</center>
