---
title: "Give an Elevator Speech"
linktitle: " Give an Elevator Speech"
menu:
  tasks:
    parent: Deliverables
    weight: 8
type: docs
weight: 8
editor_options: 
  chunk_output_type: console
---

`r blogdown::shortcode("aes-header")`

<style>
.article-style img, 
.article-style video {
  margin-left: 0;
  margin-right: auto;
  margin-top: 0rem;
  margin-bottom: 1rem;
  vertical-align: text-top;
  padding: 0;
  bottom: 0px;
  display: inline;
}
</style>

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
source(here::here("content", "com_libs.R"))
```

## SAPA Project (Optional)

If you are interested in a personality test that is ongoing, free, and run by faculty at an academic institution, take a look and consider participating the [SAPA Project](https://www.sapa-project.org/){target="_blank"} part of the [Personality Project](https://personality-project.org/){target="_blank"}^[The same people who created and maintain the `psych` package.]. They also share their [de-identified data](https://dataverse.harvard.edu/dataverse/SAPA-Project){target="_blank"} if you are interested.

## Revise and Resubmit

There are three items needed to complete the final task

1. *Elevator Speech*. Create a 1 minute (+/- 10 seconds) [elevator talk](https://uclalibrary.github.io/research-tips/deconstructing-the-elevator-speech/){target="_blank"} introducing yourself, describing the evaluation, research, or project that your instrument was used for, mode/modes of data collection and analysis/analyses, summary of findings, and its significance^[with the intent to garner interest in your study]. **Akin to an online presentation, this must be a video of you talking, though additional materials that may help the audience to understand the study content and context is welcome**. If you use a third-party service (e.g. YouTube), please provide the link. Where elevator pitches are used for *pitching an idea*, elevator speeches are conducted to *sell the value of that idea*. For more information, head over to the [Creating an Elevator Pitch or Speech](/resources/elevatortalk/) on the Resources page

2. Please submit the *Elevator Speech* to [#elevator-speech]("https://edp619fall2022.slack.com/archives/C04DCC04316"){target="_blank"} in a single posting on Slack

<br />

<center>
<p id="rounded_corners">
All submissions leading up to the proposal can be found on the main <a href="/tasks/#proposal">Tasks</a> page
<p>
</center>
