---
title: "The Organization and Graphic Presentation of Data"
linktitle: "Week 2: The Organization and Graphic Presentation of Data"
output:
  blogdown::html_page:
    toc: true
menu:
  due:
    parent: Due?
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### What to do for Week 2 after class ends^[For grading.]

```{r eval = TRUE, echo = FALSE}
unchecked <- as.character(fontawesome::fa("square", fill = "steelblue"))

checked <- as.character(fontawesome::fa("check-square", fill = "steelblue"))

wk_post <- tibble(
"eCampus?" = c(unchecked, 
               unchecked, 
               checked),

Description = c("Start a module in Data Camp that addresses some essential `tidyverse` commands.",
               "Review the R Walkthrough on the importance of data frames.",
               "Complete problems 1, 2, 3, 4, 5, 6 and 7 in Chapter 2."),

Location = c("[Link](/lesson/02-lesson/#data-camp-1)", 
             "[Link](/lesson/02-lesson/#r-walkthrough-1)",
             "[Link](/assignment/02-homeworks/#weekly-task-1)")

)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_post, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

<br />

### What to do for Week 3 before coming to class^[For preparation.]

```{r eval = TRUE, echo = FALSE}
book <- as.character(fontawesome::fa("book", fill = "steelblue"))

chalkboard <- as.character(fontawesome::fa("chalkboard", fill = "steelblue"))

lightbulb <- as.character(fontawesome::fa("lightbulb", fill = "steelblue"))

wk_pre <- tibble(
Area = c(book, 
         chalkboard, 
         lightbulb),

Description = c("Read chapter 3 in the text.",
               "Look over the text PowerPoint and corresponding notes.",
               "Watch a video on the Measures of Central Tendency.^[Optional but recommended.]"),

Location = c("[Link](/readings/03-readings/#book-stuff-1)", 
             "[Link](/lesson/03-lesson/#book-materials-1)",
             "[Link](/example/03-example/#crash-course-statistics-1)")

)

```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_pre, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```


