---
title: "The Chi-Square Test and Measures of Association"
linktitle: "Week 12: The Chi-Square Test and Measures of Association"
output:
  blogdown::html_page:
    toc: true
menu:
  due:
    parent: Due?
    weight: 10
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### What to do for Week 12 after class ends^[For grading.]

```{r eval = TRUE, echo = FALSE}
unchecked <- as.character(fontawesome::fa("square", fill = "
#4682b4"))

checked <- as.character(fontawesome::fa("check-square", fill = "
#4682b4"))

wk_post <- tibble(
"eCampus?" = c(checked, 
               unchecked),

Description = c("Begin problems 1, 2, 3, 5, 7, and 13 in Chapter 10.",
               "Take a look at the R Walkthrough on the Chi Square Distribution."),

Location = c("[Link](/assignment/12-homeworks/#assignment-1)",
             "[Link](/lesson/chisquare/)")
)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_post, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

<br />

### What to do for Week 13 before coming to class^[For preparation.]

```{r eval = TRUE, echo = FALSE}
book <- as.character(fontawesome::fa("book", fill = "steelblue"))

chalkboard <- as.character(fontawesome::fa("chalkboard", fill = "steelblue"))

lightbulb <- as.character(fontawesome::fa("lightbulb", fill = "steelblue"))

wk_pre <- tibble(

  Area = c(book, 
           chalkboard,
           lightbulb),

Description = c("Review chapter 11 in the text.",
               "Look over the text PowerPoint and corresponding notes.",
               "Watch videos on ANOVAs^[We will cover this in one week]."),

Location = c("[Link](/readings/13-readings/#book-stuff-1)",
             "[Link](/lesson/13-lesson/#textbook-class-notes-1)", 
             "[Link](/example/13-example/#crash-course-statistics-1)")

)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_pre, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

### Extra Credit

```{r eval = TRUE, echo = FALSE}
ec <- as.character(fontawesome::fa("credit-card", fill = "
#4682b4"))

wk_ec <- tibble(
  
Area = c(ec),

Description = c("An extra credit task on using Rmarkdown for reporting purposes is still available."),

Location = c("[Link](https://www.datacamp.com/){target='_blank'}")

)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_ec, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```