---
title: "Exam II"
linktitle: "Week 14: Exam II"
output:
  blogdown::html_page:
    toc: true
menu:
  due:
    parent: Due?
    weight: 13
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### What to do for Week 13 after class ends^[For grading.]

```{r eval = TRUE, echo = FALSE}
unchecked <- as.character(fontawesome::fa("square", fill = "
#4682b4"))

checked <- as.character(fontawesome::fa("check-square", fill = "
#4682b4"))

wk_post <- tibble(

"eCampus?" = c(checked,
               checked),

Description = c("Submit the Data portion of the second exam.",
               "Submit the Paper portion of the second exam."),

Location = c("[Link](https://ecampus.wvu.edu/){target='_blank'}",
             "[Link](https://ecampus.wvu.edu/){target='_blank'}"
             )

)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_post, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

### Extra Credit

```{r eval = TRUE, echo = FALSE}
ec <- as.character(fontawesome::fa("credit-card", fill = "
#4682b4"))

wk_ec <- tibble(
  
Area = c(ec),

Description = c("An extra credit task on using Rmarkdown for reporting purposes has posted."),

Location = c("[Link](https://www.datacamp.com/){target='_blank'}")

)


```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_ec, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```