---
title: "The Organization and Graphic Presentation of Data"
linktitle: "Week 2: The Organization and Graphic Presentation of Data Content"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  materials:
    parent: Content
    weight: 2
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

`r blogdown::shortcode("aes-header")`

```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(fontawesome)
library(here)
library(DT)
library(scales)
library(latex2exp)
library(showtext)
font_add_google("Roboto Condensed", "roboto")
showtext_auto()
```

## Stock Textbook Notes

```{r echo=FALSE}

pptx_location <- "/lecture_notes/Week 2/SSDS_Ch2.pptx"
docx_location <- "/lecture_notes/Week 2/SSDS_Ch2.docx"

powerpoint_link <- function() {
  paste0("<a target='_blank' href=\"", pptx_location, "\">", as.character(fa("file-powerpoint", fill = "#d04423", width = "2em")), "</a>")
}

word_link <- function() {
  paste0("<a target='_blank' href=\"", docx_location, "\">", as.character(fa("file-word", fill = "#00a4ef", width = "2em")), "</a>")
}

textitems <- tibble(
  
  pptx <- c("Chapter 2 PowerPoint",
               powerpoint_link()),
  
  docx <- c("Chapter 2 Notes",
            word_link())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(textitems, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

## In Class Presentations
For all slideshows, you may move back and forth using <kbd>←</kbd> and <kbd>→</kbd> and toggle fullscreen by pressing <kbd>F</kbd>. Just press <kbd>O</kbd>[^1] at any point in your slideshow and a display of all slides, called tile view, will appear. Click on a slide to go there or press <kbd>O</kbd> to exit tile view. For more options, press <kbd>H</kbd> for help.

### Concepts

<center>
```{r echo = FALSE}
knitr::include_url("/slides/Week 2/Slides-Week-2.html")
```
</center>

```{r echo=FALSE}

html_location <- "/slides/Week 2/Slides-Week-2.html"
pdf_location <- "/slides/Week 2/Slides-Week-2.pdf"

html_link <- function() {
  paste0("<a target='_blank' href=\"", html_location, "\">", as.character(fa("person-chalkboard", fill = "#7ead86", width = "3em")), "</a>")
}

pdf_link <- function() {
  paste0("<a target='_blank' href=\"", pdf_location, "\">", as.character(fa("file-pdf", fill = "#f40f02", width = "2em")), "</a>")
}

slideshowitems <- tibble(
  
  html <- c("Full Screen Slideshow",
               html_link()),
  
  pdf <- c("Presentation PDF",
            pdf_link())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(slideshowitems, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

### R Walkthrough

<center>
```{r echo = FALSE}
knitr::include_url("/slides/Week 2/Slides-Week-2R.html")
```
</center>

```{r echo=FALSE}

htmlR_location <- "/slides/Week 2/Slides-Week-2R.html"
pdfR_location <- "/slides/Week 2/Slides-Week-2R.pdf"

htmlR_link <- function() {
  paste0("<a target='_blank' href=\"", htmlR_location, "\">", as.character(fa("person-chalkboard", fill = "#7ead86", width = "3em")), "</a>")
}

pdfR_link <- function() {
  paste0("<a target='_blank' href=\"", pdfR_location, "\">", as.character(fa("file-pdf", fill = "#f40f02", width = "2em")), "</a>")
}

slideshowRitems <- tibble(
  
  htmlR <- c("Full Screen Slideshow",
               htmlR_link()),
  
  pdfR <- c("Presentation PDF",
            pdfR_link())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(slideshowRitems, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

[^1]: For <b>O</b>verview
