---
title: "Sampling and Sampling Distributions"
linktitle: "Week 7: Sampling and Sampling Distributions"
output:
  blogdown::html_page:
    toc: true
menu:
  materials:
    parent: Content
    weight: 7
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

`r blogdown::shortcode("aes-header")`

```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(fontawesome)
library(here)
library(DT)
library(scales)
library(latex2exp)
library(showtext)
font_add_google("Roboto Condensed", "roboto")
showtext_auto()
```

## Stock Textbook Notes

```{r echo=FALSE}

pptx_location <- "/lecture_notes/Week 7/SSDS_Ch6.pptx"
docx_location <- "/lecture_notes/Week 7/SSDS_Ch6.docx"

powerpoint_link <- function() {
  paste0("<a target='_blank' href=\"", pptx_location, "\">", as.character(fa("file-powerpoint", fill = "#d04423", width = "2em")), "</a>")
}

word_link <- function() {
  paste0("<a target='_blank' href=\"", docx_location, "\">", as.character(fa("file-word", fill = "#00a4ef", width = "2em")), "</a>")
}

textitems <- tibble(
  
  pptx <- c("Chapter 6 PowerPoint",
               powerpoint_link()),
  
  docx <- c("Chapter 6 Notes",
            word_link())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(textitems, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

## In Class Presentations
For all slideshows, you may move back and forth using <kbd>←</kbd> and <kbd>→</kbd> and toggle fullscreen by pressing <kbd>F</kbd>. Just press <kbd>O</kbd>[^1] at any point in your slideshow and a display of all slides, called tile view, will appear. Click on a slide to go there or press <kbd>O</kbd> to exit tile view. For more options, press <kbd>H</kbd> for help.

### Concepts

<center>
```{r echo = FALSE}
knitr::include_url("/slides/Week 7/Slides-Week-7p1.html")
```
</center>

```{r echo=FALSE}

html_locationp1 <- "/slides/Week 7/Slides-Week-7p1.html"
pdf_locationp1 <- "/slides/Week 7/Slides-Week-7p1.pdf"

html_linkp1 <- function() {
  paste0("<a target='_blank' href=\"", html_locationp1, "\">", as.character(fa("person-chalkboard", fill = "#7ead86", width = "3em")), "</a>")
}

pdf_linkp1 <- function() {
  paste0("<a target='_blank' href=\"", pdf_locationp1, "\">", as.character(fa("file-pdf", fill = "#f40f02", width = "2em")), "</a>")
}

slideshowitemsp1 <- tibble(
  
  htmlp1 <- c("Full Screen Slideshow",
               html_linkp1()),
  
  pdfp1 <- c("Presentation PDF",
            pdf_linkp1())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(slideshowitemsp1, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

<center>
```{r echo = FALSE}
knitr::include_url("/slides/Week 7/Slides-Week-7p2.html")
```
</center>

```{r echo=FALSE}

html_locationp2 <- "/slides/Week 7/Slides-Week-7p2.html"
pdf_locationp2 <- "/slides/Week 7/Slides-Week-7p2.pdf"

html_linkp2 <- function() {
  paste0("<a target='_blank' href=\"", html_locationp2, "\">", as.character(fa("person-chalkboard", fill = "#7ead86", width = "3em")), "</a>")
}

pdf_linkp2 <- function() {
  paste0("<a target='_blank' href=\"", pdf_locationp2, "\">", as.character(fa("file-pdf", fill = "#f40f02", width = "2em")), "</a>")
}

slideshowitemsp2 <- tibble(
  
  htmlp2 <- c("Full Screen Slideshow",
               html_linkp2()),
  
  pdfp2 <- c("Presentation PDF",
            pdf_linkp2())
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(slideshowitemsp2, 
      col.names = c("", ""),
      escape = FALSE,
      align = 'cc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1:2, width = "20em", extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

[^1]: For <b>O</b>verview

