---
title: "Endgame"
linktitle: "Week 15: Endgame"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  materials:
    parent: Materials
    weight: 15
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

## Reflecting on Program Evaluation
Please take and complete the survey ***Reflecting on Program Evaluation*** that has been sent to your e-mail. While I ask that you please fill it out truthfully, please note there is no right or wrong answer. This is just a follow-up assessment of what you may or may not have learned within the class. If you did not receive an invite, please let me know as soon as possible!

## Post and Look Through Evaluations/Presentations

- Post your evaluation to both eCampus and <a href='https://2022edp617.slack.com/archives/C03ED73K08G' target='_blank' style='color: #ff8384;'><font size='4px'>#evaluation-report</font></a>. <b>Make sure to look through and comment on all of the others!</b>

- Post your presentation to both eCampus and <a href='https://2022edp617.slack.com/archives/C03DLHDTQTX' target='_blank' style='color: #ff8384;'><font size='4px'>#presentation-of-results</font></a>. 

## Acknowledgement 

Email a copy of the response you receive from the primary stakeholder(s)/sponsor(s) acknowledging that they have received your evaluation report.
