---
title: "The What and Why of Statistics"
linktitle: "Week 1: The What and Why of Statistics"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Assignments
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

### Class Slack Account Access
Please sign up for Slack!
  1. Go to the course [Slack](2020edp613.slack.com){target="_blank"} account 
  2. Register if you already do not have an account. Note that you do not have to use your WVU account, but its not a bad idea.
  3. Head to to the channel #introduce-yourself and well introduce yourself by tell everyone about yourself, what you hope to achieve out of this course, and something about you that really defines who you are. For example, here is something about me:
<br>
*I teach data visualization BUT I am also about 40% colorblind! How do I know what color to use? Take EDP 693C: Data Visualization in the Spring to find out!* ^[Shameless plug]
  4. (optional) Provide a picture if you are willing. I am a very visual person as are many other people so pictures help a great deal. However, you are not mandated to do so!<br>

### Homework
Chapter 1 Exercises: 3, 4, 6, 7, and 8. Please turn it in to the Submission Portal on [ecampus](https://ecampus.wvu.edu/){target="_blank"} by 11:59 PM next Wednesday.
:::
