---
title: "Abhik Ranjan Roy"
author: "Abhik Ranjan Roy"
date: "`r Sys.Date()`"
---

```{r, echo=FALSE}
source_rmd <- function(file, local = FALSE, ...){
  options(knitr.duplicate.label = 'allow')

  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(file, output=tempR, quiet = TRUE)

  envir <- globalenv()
  source(tempR, local = envir, ...)
}
```

```{r, echo=FALSE}
source_rmd("cv-html.Rmd")
source_rmd("resume-html.Rmd")
source_rmd("pubs-html.Rmd")
```

```{r, echo=FALSE}
source_rmd("cv-pdf.Rmd")
source_rmd("resume-pdf.Rmd")
source_rmd("pubs-pdf.Rmd")
```

```{r, echo=FALSE}
source("convert2html.R")
pagedown::chrome_print("cv-pdf.Rmd", output = "cv.pdf", timeout = 100)
pagedown::chrome_print("resume-pdf.Rmd", output = "resume.pdf")
pagedown::chrome_print("pubs-pdf.Rmd", output = "pubs.pdf", timeout = 100)
file.remove('cv-pdf.html')
file.remove('resume-pdf.html')
file.remove('pubs-pdf.html')
file.remove('cv-pdf.pdf')
file.remove('resume-pdf.pdf')
file.remove('pubs-pdf.pdf')
```
