---
title: "Sourcing Resources"
linktitle: "Week 2: Sourcing Resources"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  tasks:
    parent: Tasks
    weight: 2
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

### Breaking Down Literature

1. Open the `Literature_Review_Prep.xlsx` file which is part of this week's [download](/materials/02-materials/#downloads)

2. Carefully look over the three sections and corresponding examples given by tabs.

3. Pair up with your partner.

4. Choose *one* paper from the downloads through a consensus.

5. Independently, fill out the applicable sections within each tab. *Please refrain from comparing your tables at this time.*

### Continue CITI Ethics Training
Completion of all necessary [CITI modules](https://human.research.wvu.edu/get-started/training/citi-ethics-training) is not only mandated, but if you conduct research in any capacity and are not certified consequences can be dire including receiving jail time. The Ethics Training is an educational program to teach you about the protection of human subjects in research. In this course, you are required to complete the <b>Social & Behavioral Research Investigators Basic Course</b>. Use the link given above to get registered. Completion of the entire set is due in **three weeks**. You can upload a copy of the completion certificate to [eCampus](https://ecampus.wvu.edu/) at any time.
