---
title: "Causation and Criteria"
linktitle: "Week 4: Causation and Criteria"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  tasks:
    parent: Tasks
    weight: 4
type: docs
weight: 1
---

## Writing

### Responses

Please create **two separate responses** for <a href="https://edp617spring2023.slack.com/archives/C04LEHZTFFD" target="_blank" style='color:#ff8384;'>#wk3-criteria</a> on Slack<sup>1</sup>. 

### Posting
After going through this week's [readings](/readings/04-readings), address the following in a single post on the channel <a href="https://edp617spring2023.slack.com/archives/C04MUEDMDSM" target="_blank" style='color:#5eb0e5;'>#wk4-hypotheticals</a>

  + Given a list of multiple criteria given to you by both sponsors and stakeholders prior to conducting an evaluation, how would you determine which are more important than others?
  
  + Can we determine causality in every circumstance?
  
## Doing
  
### (The Possible Problems with) Causality and Program Evaluation

If you need a refresher on correlations and causation, take a few minutes to watch the fantastic breakdown below

<center>
<iframe src="https://www.youtube.com/embed/HUti6vGctQM" width="640" height="360" frameborder="0" allow="fullscreen" style="display: block; margin: 0 auto 1rem;"></iframe>
</center>

Now take a look at a brief from UNICEF addressing causal attributions on (impact) program evaluations 

<center>
<iframe src="https://www.youtube.com/embed/4lv3DJFBLqI" width="640" height="360" frameborder="0" allow="fullscreen" style="display: block; margin: 0 auto 1rem;"></iframe>
</center>

### Deliverable

Your first deliverable - [Evaluation Prospectus](/deliverables/01-evaluation-prospectus/) - is due at the end of this week.
