---
title: "Bivariate Tables"
linktitle: "Week 10: Bivariate Tables"
toc: true
output:
  rmarkdown::html_document:
    toc: true
menu:
  tasks:
    parent: Homeworks
    weight: 10
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(fontawesome)
library(here)
library(patchwork)
```

`r blogdown::shortcode("aes-header")`

### Homework
```{r icontibble, echo=FALSE, message=FALSE}
book <- tibble(
  
  chapter <- c("9"),
  
  exercises <- c("1, 2, 3, 4, 5"),
  
  problems <- c("Social Statistics for a Diverse Society"),
  
  pages <- c("237-240"),
  
  .name_repair = "minimal"
  
)
```

<center>
```{r, echo=FALSE}
book %>%
  kbl(col.names = c("Chapter", "Problems", "Source", "Pages"), 
      "html", 
      escape = FALSE,
      align = 'clll') %>%
  column_spec(1, bold = TRUE) %>%
  row_spec(0:nrow(book), extra_css = 'vertical-align: middle !important;', background = "#212121", color = "#ffffff")
```
</center>

Notes: 

- Please submit this at the beginning of class next week.
- Remember to follow the [homework guidelines](/tasks/#homeworks) for consideration.

<!--
to the Submission Portal on [ecampus](https://ecampus.wvu.edu/){target="_blank"} by 11:59 PM next Wednesday.<br>
-->

### Solutions

*Posted after class day and time next week.*

<!--
*Note: To stay consistent with the general literature, the* $\chi^2$ *value obtained will be referenced by the variable* $\chi^2_{obt}$.

<details><summary>1</summary>
<p>
a. <span class="boxed">The *independent variable* is sex</span> while <span class="boxed">the *dependent variable* is fear of walking alone at night</span>.
<div align="center">
<div style="width: 50%; margin:0 left;text-align: left;">
```{r, echo=FALSE, eval=TRUE}

walking1 <- tibble(

Choice = c("Yes", 
 "No"),

Male = c("2 (22%)", 
"7 (78%)"),

Female = c("8 (73%)", 
 "3 (27%)"),
) 

walking1 %>%
kable(align = 'lcc',
 booktabs = TRUE, 
 linesep = "",
 escape = FALSE) %>%
kable_styling(full_width = FALSE) 
```
</div>
</div>

b. Approximately $73$% of women are afraid to walk alone in their neighborhoods at night, whereas approximately $22$% of men said the same. This amounts to about a <span class="boxed">$51$% difference between women and men who are not afraid to walk alone at night</span>, indicating a strong relationship. It is important to keep in mind that our small sample size limits the generalizability of these results. 

c. There does not appear to be much of a relationship between homeownership and fear of walking alone at night. The majority in both homeownership categories ($54$% and $55$%) indicated that <span class="boxed">they were not afraid of walking alone at night in their neighborhood</span>. 
<div align="center">
<div style="width: 50%; margin:0 left;text-align: left;">
```{r, echo=FALSE, eval=TRUE}
walking2 <- tibble(

Response = c("Yes", 
 "No"),

Male = c("4 (44%)", 
"5 (54%)"),

Female = c("5 (45%)", 
 "6 (55%)"),
) 

walking2 %>%
kable(align = 'lcc',
 booktabs = TRUE, 
 linesep = "",
 escape = FALSE) %>%
kable_styling(full_width = FALSE) 
```
</div>
</div>
</p>
</details>

<details><summary>2</summary>
<p>
a. The <span class="boxed">the *independent variable* is AGE</span> independent variable and measured in categories.

b. The independent variable <span class="boxed">*AGE*</span> is ordinal while the dependent variable <span class="boxed">*PRES16* is nominal</span>. 

c. There appears to be a relationship between age and who a respondent voted for in the 2016 U.S. presidential election. Of those surveyed, $55.4$% voted for Clinton, whereas only $35.4$% voted for Trump. However, far more younger people voted for Clinton than Trump. Take for example the categories 18–29 and 30–39. Of those 18–29 years of age, $65.7$% voted for Clinton as compared to $19.2$% of those of the same age group that voted for Trump ($19.2$%). Similarly, $61.1$% of those between 30 and 39 voted for Clinton, whereas only $26.8$% of the same age group voted for Trump.
</p>
</details>

<details><summary>3</summary>
<p>
a. Based on the student’s argument, <span class="boxed">the *independent variable* is race</span> and <span class="boxed">the *dependent variable* is home ownership</span>.

b. We have $$\dfrac{539}{857} \approx 0.6289$$ or about <span class="boxed">$63$%</span>.

c. <span class="boxed">There appears to be a relationship between race and home ownership</span>. While $63$% of those surveyed report owning a home, far less Black respondents report such ($41.3$%) than White respondents ($67.7$%). Furthermore, $58.7$% of Black respondents rent as compared to $32.3$% of White respondents.
</p>
</details>

<details><summary>4</summary>
<p>
a. The <span class="boxed">*independent variable* is the respondent's age</span> while the <span class="boxed">*dependent variable* is home ownership</span>.

b. <span class="boxed">Yes</span>, there appears to be a relationship between age and home ownership. While $51$% of all those surveyed are home owners, a far greater percentage of those 50–59 years-of-age are home owners ($65.7$%) than all other age categories, especially those between 18 and 29 years-of-age.

c. *Possible answers*: student loan debt - a person might not be able to save up for a down payment - and city of residence - home ownership in San Francisco or New York City is impossible for many people due to home values.
</p>
</details>

<details><summary>5</summary>
<p>
<span class="boxed">There appears to be a relationship between race and the frequency of being drunk in the last 12 months</span>. The majority of students ($60$%) are likely to report not being drunk in the last 12 months. However, the percentage of students being drunk at least 3 or more times is highest for Whites ($28$%), followed by Hispanic ($16$%) and Black ($11$%) students.
<div align="center">
<div style="width: 50%; margin:0 left;text-align: left;">
```{r, echo=FALSE, eval=TRUE}
drunk <- tibble(

Frequency = c("None", 
 "1-2 times",
 "3-5 times",
 "> 6 times",
 "Total"),

Black = c("359 (75%)", 
"63 (13%)",
"24 (5%)",
"31 (6%)",
"477 (99%)"),

White = c("1081 (55%)", 
"342 (17%)",
"168 (8%)",
"389 (20%)",
"1980 (100%)"),

Hispanic = c("480 (67%)", 
"125 (17%)",
"50 (7%)",
"64 (9%)",
"719 (100%)"),

Total = c("1920 (60%)", 
"530 (17%)",
"242 (8%)",
"484 (15%)",
"3176 (100%)")

) 

drunk %>%
kable(align = 'lccccc',
 booktabs = TRUE, 
 linesep = "",
 escape = FALSE) %>%
kable_styling(full_width = FALSE) 
```
</div>
</div>
</p>
</details>
-->
