---
title: "Proposal"
linktitle: "Proposal"
menu:
  tasks:
    parent: "Final"
    weight: 1
type: docs
weight: 3
editor_options: 
  chunk_output_type: console
---

<style>
  .hvr-sweep-to-left {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0);
    position: relative;
    -webkit-transition-property: color;
    transition-property: color;
    -webkit-transition-duration: 0.25s;
    transition-duration: 0.25s;
  }

.hvr-sweep-to-left:before {
  content: "";
  position: absolute;
  z-index: -1;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: #175676;
    -webkit-transform: scaleX(0);
  transform: scaleX(0);
  -webkit-transform-origin: 100% 50%;
  transform-origin: 100% 50%;
  -webkit-transition-property: transform;
  transition-property: transform;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-timing-function: ease-out;
  transition-timing-function: ease-out;
}

.hvr-sweep-to-left:hover, .hvr-sweep-to-left:focus, .hvr-sweep-to-left:active {
  color: white;
}

.hvr-sweep-to-left:hover:before, .hvr-sweep-to-left:focus:before, .hvr-sweep-to-left:active:before {
  -webkit-transform: scaleX(1);
  transform: scaleX(1);
}
</style>

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

## Final Proposal

Construct a one paragraph case for a population^[A population does not necessarily refer to people.] 

1. that needs to be researched or evaluated, 

2. why it should be be studied, and 

3. how the data is a good fit for a network analysis

Please submit this to 
[#eCampus](https://ecampus.wvu.edu/){target='_blank'} no later than November 14 at 11:59 PM.^[Late proposals will immediately receive a 50% reduction in score and will only be accepted up to 24 hours past the deadline.]
