---
title: "The Normal Distribution"
linktitle: "Week 5: The Normal Distribution"
output:
  blogdown::html_page:
    toc: true
menu:
  due:
    parent: Due?
    weight: 5
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(dplyr)
library(fontawesome)
library(knitr)
library(kableExtra)
```

### What to do for Week 5 after class ends^[For grading.]

```{r eval = TRUE, echo = FALSE}
unchecked <- as.character(fontawesome::fa("square", fill = "steelblue"))

checked <- as.character(fontawesome::fa("check-square", fill = "steelblue"))

wk_post <- tibble(
"eCampus?" = c(unchecked, 
               unchecked,
               checked),

Description = c("Complete a module in Data Camp focused on basic descriptive statistics and an introduction to probability.",
              "Go through the NFL and Pipes R walkthrough",
               "Complete problems 1, 2, 5, 6, 7, 8, 11 and 12 in Chapter 5."
               ),

Location = c("[Link](/lesson/05-lesson/#data-camp-1)", 
             "[Link](/walkthroughs/nfl/nflpipes/)",
             "[Link](/assignment/05-homeworks/#weekly-task-1)"
             )

)
```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_post, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

<br />

### What to do for Week 6 before coming to class^[For preparation.]

```{r eval = TRUE, echo = FALSE}
book <- as.character(fontawesome::fa("book", fill = "steelblue"))

chalkboard <- as.character(fontawesome::fa("chalkboard", fill = "steelblue"))

lightbulb <- as.character(fontawesome::fa("lightbulb", fill = "steelblue"))

wk_pre <- tibble(
Area = c(book, 
         chalkboard, 
         lightbulb),

Description = c("Read chapter 6 in the text.",
               "Look over the text PowerPoint and corresponding notes.",
               "Watch videos on Experimental Designs and Sampling Methods.^[Optional but recommended.]"),

Location = c("[Link](/readings/06-readings/#book-stuff-1)", 
             "[Link](/lesson/06-lesson/#book-materials-1)",
             "[Link](/example/06-example/#crash-course-statistics-1)")

)

```

```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
kable(wk_pre, 
      escape = FALSE,
      align = 'clc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "30em") %>%
  column_spec(3, width = "10em")
```

