---
title: "About the Readings"
menu:
  content:
    parent: Overview
    weight: 1
type: docs
weight: 1
---

## The Course Text
Each class session has a set of required readings that you should complete ***before*** doing anything else. It also allows you to ask questions prior to moving on! With that said, think of the text as a reference, in that

- it contains a lot of information that you may use but probably not right now, and
- it gives you a basis to ask intelligent questions. 

So you should absolutely read it to get a basis but in the long run, you will learn more from this course by doing.

## The Course Nontext
Many of us are visual learners with me included so a lot of what I provide outside of the text is visually based. Resources such as presentations, videos, visualizations, walkthroughs, etc. take a lot of time to construct so please take some time to go through them. Is the production quality Hollywood? No because I'm a professor at a public university, have three children and drive a car with duct tape on it BUT they'll be decent. Also I can never sound like Morgan Freeman but other than that, I am always open to suggestions so if you have any, please send them along!
<br>
<br>
*Pictures are better than words because some words are big and hard to understand.* 
<br> 
- Peter Griffin

