---
title: "Who Are You Really?"
linktitle: "Week 1: Who Are You Really?"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Weekly Tasks
    weight: 1
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

## First Timers Note
You'll see class related tasks posted here on a weekly basis. 

### Class Slack Account Access
Most important task of the week - well to me at least - is to

  1. Go to the course [Slack](2021edp617.slack.com){target="_blank"} account 
  2. Register if you already do not have an account. Note that you do not have to use your WVU account, but its not a bad idea.
  3. Head to to the channel [`#introduce-yourself`](https://2021edp617.slack.com/archives/C01K4D3HJBU){target="_blank"} and well introduce yourself by tell everyone about yourself, what you hope to achieve out of this course, and something about you that really defines who you are. For example, here is something about me:
<br>
*I teach data visualization BUT I am also about 40% colorblind! How do I know what color to use? Take EDP 693E: Data Visualization this term to find out!* ^[Shameless plug; face-to-face only]
  4. (optional) Provide a picture if you are willing. I am a very visual person as are many other people so pictures help a great deal. However, you are not mandated to do so!
<br>

### Verify Qualtrics Account Login
You may end up using a survey in this course so its a good idea to go to the [WVU Qualtrics login page](https://wvu.qualtrics.com){target="_blank"} and simply make sure you can login. If you are unable to do so, please submit a [ticket to IT](https://wvu.teamdynamix.com/TDClient/1976/Portal/Requests/ServiceDet?ID=9102){target="_blank"} or give them a ring at <a href="tel:3042934444">304-293-4444</a> as soon as possible.
<br>

### Drawing Evaluations
Get a blank piece of paper and writing utensil or use a computer program to draw a picture of the first thing that comes to your mind when you hear the word “Evaluation”. Think about what that picture means to you and then write a post describing the picture you drew and explaining why you think that was the picture that first came to your mind in relation to “Evaluation”. If you drew a picture, scan your picture and attach it to your post. Post on the [`#pictures-of-evaluation`](https://2021edp617.slack.com/archives/C01KL7W6H6V){target="_blank"} discussion board on Slack.

:::