---
title: "80% of Your Time with Data is Dedicated to Wrangling!"
linktitle: "Week 2: 80% of Your Time with Data is Dedicated to Wrangling!"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Exercises
    weight: 2
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

## Task: Assessing Common Descriptives

Load the `fivethirtyeight` package and scroll through the data sets or alternatively click [here](https://github.com/fivethirtyeight/data){target="_blank"} to see the FiveThirtyEight GitHub repository. Locate a response set that is derived from a survey. 

Run some basic descriptive statistics on the set. What you explore and/or report on is up to you. What I really want is for you to get comfortable (well as much as possible) with writing syntax. The more you try, the more I can comment on! Please turn in 

1. your R script (.R format) with your name in the upper left-hand corner beside of a hashtag # so it appears as a comment. Please please please make sure to provide comments for clarification and format your script so that it is clear and understandable. An example scripts is included which can be accessed [here](/exscripts/example_script.R). You may either right click and download the file to open it or copy and paste the content to your own blank script.

If you want some help with commands, give these sites a try:

- [Quick-R by DataCamp](https://www.statmethods.net/stats/descriptives.html){target="_blank"}
- [Summary and Analysis of Extension Program Evaluation in R](https://rcompanion.org/handbook/C_02.html){target="_blank"}
- [STHDA - Statistical tools for high-throughput data analysis](http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics){target="_blank"}

... and if you're still stuck, ask a peer and then please contact me!

2. a maximum one page 12-point font double spaced description of what (a) the data set was about, (b) you explored and (c) you wish you knew how to do in R to better understand the data set.  

Extra credit may be awarded for those who apply statistics beyond descriptives. If you want some fun ideas, run the following and select some of the user-contributed scripts

```{r echo=TRUE, eval=FALSE}
vignette("user_contributed_vignettes", package = "fivethirtyeight")
```

:::
