---
title: "Pirates Cause Global Warming"
linktitle: "Week 4: Pirates Cause Global Warming"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Exercises
    weight: 4
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

## Task: RFPs with Reliability and Validity

A request for proposal (RFP) is a dispersed document that solicits proposals by an agency, company or organization interested in conducting an evaluation. For example, you can go to the [American Evaluation Association's (AEA) Career Center](https://careers.eval.org/){target="_blank"} and simply type `rfp` in the Keyword or Job Title box to take a look at current opportunities and their respective requirements. 

These types of proposals are often lucrative but highly competitive.
Since most RFPs are submitted without any opportunities for follow-ups or clarifications, stakeholder or sponsor will pick the one that has the greatest detail, clearly written, and does not promise too little or even too much! 

The final project in this course is derived from a much larger study of what employers look for in an evaluator. The requirements of  particular task is a carbon copy of findings related to RFPs specifically where documents were analyzed from a systematic sample of two years of RFPs posted on the website listed above and [AEA's Jobs/RFPs](https://www.eval.org/p/cm/ld/fid=113){target="_blank"} site as well. 

While you certainly won't be writing an entire RFP, the criteria will give you practice in addressing an instrumentation and measurement section. Now on to the fun part

<hr />

First either choose to use an existing instrument or develop one yourself. Now please submit a proposal outlining

- Proposed test items
  - a description of a current or developing instrument you wish to study including what the entire piece is intended to assess including details related to items or groups of items that may be or are measuring differing constructs.
  - an explanation of (a) how the items were decided upon and (b) how the number of items was determined
  
- Proposed Reliability Assessment
  - An explanation of how the administration (and/or scoring) of the test will permit you to determine its reliability. Please be  specific about which reliability coefficient you are proposing and use the appropriate terminology (e.g., test-retest reliability will be computed by correlating scores obtained from administering the test to a randomly selected group of program participants and re-administering the test to the same group on six months later)

- Proposed Validity Assessment
  - Identification and description of the group for which you want the test to be valid for.
  - Descriptions of at least one approach for computing the content validity, concurrent validity and predictive validity of your test.

The deadline for this RFP is Thursday, August 6 by 11:59PM. The structure and page length is typical for an average sized multi year RFP that a single evaluator would be able conduct ion an individual basis. The proposal should 

- be three to five pages double spaced with both front and back used with 12 point Times New Roman font; 
- include both () your name and a working title in the header such that it repeats on every page and (b) page numbers;
- have a full working or current draft of the proposed instrument attached in an appendix.
- follow all APA 7th Edition guidelines. 
- have support (e.g. references of previous studies) where *an assertion is made*. 
- be clearly and concisely written, You simply do not have enough space to get wordy, so read and critique your proposal over and over until you are simply sick of it. If you get to the point where all criteria are met but you are at the "to hell with this and him" stage, then the proposal is probably in a good state to be submitted.
:::
