---
title: "Evaluation Proposal"
linktitle: "Week 6: Evaluation Proposal"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Evaluation Proposal
    weight: 1
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

<style>
ul {
    margin-left: 1.5em;
}
</style>

## <span style="color:#0392cf">Evaluation Proposal</span>

### <span style="color:#073965">Submission</span>
[eCampus](https://ecampus.wvu.edu){target="_blank"}

### <span style="color:#074276">Type</span>
Teams^[Students in the course must participate in the writing process in a group oriented setting.]

### <span style="color:#0F4C81">Description</span>
At this point you should have a decided on a program to evaluate. 

### <span style="color:#155790">Criteria</span>
At the latest, as soon as your team have submitted the [Needs Assessment](/assignment/05-needs-assessment/), please begin working on this assignment. Information and pieces from that task will help provide a context for the proposal, but the narrative should be dedicated to what the team **will actually do** in the evaluation. You must have a clear and concise description of intent, what is needed to be accomplished, and how results will be delivered.

### <span style="color:#1B609D">Structure</span>
This submission is due **one week**^[Please check eCampus for the exact due date.] after the Needs Assessment. The following components are required for your submission in the order listed below and must be uploaded as a single cohesive document . Barring items 1 and 2, all other criteria must be in standard APA 7th edition formatting. The following components are required for your submission in order and must be submitted as a single document^[It is highly unlikely that a score will be changed unless there is an egregious error on my end so please check your entire document over prior to submission.]

1. A cover page with your name

  - Every group member's name in the upper left-hand corner in alphabetical order in accordance to their last name. For those teams that have assigned internal roles, please include those titles in parentheses. 
  - The title of this task – **Evaluation Proposal** – in the middle of the page.
  
2. No running head

3. A Table of Contents 

3. The Body fulfilling the requirements described below

4. A references section^[If necessary]

5. Any additional  materials you believe will help in ensuring that your proposal is complete and valid. Classify these by type and separate them into differing Appendices. There is no limit to the number of Appendices.^[Optional] 

6. Filename in *either* of the following formats

- `teamname_evaluationproposal.docx` 

- `teamname_evaluationproposal.pdf`


### <span style="color:#1B609D">Body</span>

As you construct this, please use the items in **bold** as headings and subheadings. These topics are what you should cover, at minimum, in your proposal. Your answers should be brief, to the point and must address the given topic area explicitly. Remember to maintain a continuous narrative and proper flow. This assignment usually fills seven (7) to 12 double spaced pages. 

### <span style="color:#1B609D">General Outline</span>

+ **Introduction**. A brief description of the program concentrating on what areas of importance you discovered in the Needs Assessment. This should be brief and is typically no more than one (1) page maximum.

+ **Justification**. You must include evidence from, at minimum, the items we have covered in the course so far as a defense for your approach. In this case, you are providing an evidence-based argument for the way you want to conduct the study. At minimum, the topics covered here should address an intended evaluative framework/orientation/model/approach that will guide your program evaluation and answer how this construct will be well-suited to evaluate the program.

+ **Methodology**. This section will be the largest and most detailed component. This is will be your chance to detail the intended evaluative process and to justify your methodological approach. At minimum, please cover the following where applicable

  + **Sampling frame**. A description of the overall targeted population and sample that you have drawn or will draw. This includes a description of the primary stakeholders, or those you are studying, and secondary stakeholders, or those who are not directly affected by the program.
  
  + **Assessment of Values**. Address what set of values you will be using in your evaluation. This should be very explicit, and you must explain where these came from?
  
  + **Existing Data**. If applicable, provide a description of what existing data will you be using within your evaluation, how you plan on accessing that data and what form the raw data will be in.
  
  + **Data Collection**. Discuss what data you will utilize within your evaluation, how you will collect that data, what instruments and/or materials you will be using or plan to use, and how you will gain permission from those who are participating.
  
  + **Analysis**. Provide a narrative on the type of raw data you will have. Address how you intend to analyze the quantitative, qualitative, and or mixed data you will have. 
  
  + **Reporting Cycle**. Briefly discuss how the results will be reported to the sponsor, when you intend to do so, and if you are intending to provide an interim report.
  
+ **Statement of Intent**^[May earn an extra 10% on the final score.]. On a separate page, please provide a one paragraph statement of intent on whether you plan to use or publish your work beyond the framework of this course and your corresponding reasoning. 

  - <details><summary>If you ***do*** intend to publish, then please select this</summary>
<p>
Your team submission should include the following components separated into three parts
    1. **external deliverable**. Your final report submitted to the sponsor that is written to be easily accessible and consumable
    2. **evaluation assessment**^[Includes a significant amount of detail regarding activities, criteria satisfied, areas of missingness, timeline, and other possible legal concerns should an audit occurs.]. Form a *coherent* and *detailed* narrative addressing what you would do differently given the chance to perform your evaluation over again. You can think of this as a reflection of all activities and personnel associated with the evaluation. Specificity, clarity and distinct connections to the course content will be key here.
    3. (optional) **client authorization**. If anybody on your team intends to use this report outside of this course in any capacity (e.g. as an example of work), you must submit a signed release from the sponsor. This serves as a binding document.    
</p>
</details>

  - <details><summary>If you ***do not*** intend to publish, then please select this</summary>
<p>
Your team submission should include the following components separated into three parts
    1. **external deliverable**. Your final report submitted to the sponsor that is written to be easily accessible and consumable
    2. **original manuscript**^[An authorship agreement with me is required for this option.] A solid and coherent draft of a publication based off of your evaluation.
    3. (optional) **client authorization**. You must submit a signed release from the sponsor permitting the use of the evaluation for the purposes of an academic publication. This serves as a binding document.   
</p>
</details>

Notes:

  - Using your evaluation in any capacity outside of the course requires a client authorization.
  - An IRB submission may also also required but should not be included in your submission. You may however submit this request through the [WVU+kc system](https://oric.research.wvu.edu/wvu-kc){target="_blank"}.


*Please be sure of your intent! The way in which I consult you will differ based on your statement. This is extremely important primarily due to writing styles, in that the narrative in an academic report often differs significantly from the body of an academic paper.*

:::
