---
title: "From a Certain Poimt of View... A Certain Point of View?"
linktitle: "Week 6: From a Certain Poimt of View... A Certain Point of View?"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Exercises
    weight: 5
type: docs
weight: 5
editor_options: 
  chunk_output_type: console
---

## Idea: Principle Component Analysis (PCA)

### Locating Data

You'll want to first locate a raw data set with (a) survey responses using the same column and row formatting structure as the set that was used in the example AND (b) a code book that has clearly defined the variables (columns). Make sure you keep an accurate record of what data set was used and where you got it from.

Where can you find data you ask? Oh you didn't. Well its too late now so here are some suggestions. These are given in alphabetical order without any preferential ranking:

- [AWS public datasets](https://registry.opendata.aws/){target="_blank"} - This stands for Amazon Web Service and yes its that Amazon. Believe it or not, Amazon is one of the largest providers of APIs (acronym for *application programming interface* which is a fancy way to say a service where computer programs can talk to each other), data analytics (fancy of way of saying that a computer is being used for stats), data processing (fancy way of say how efficient data can be analyzed, rearranged, whatever), and storage cloud computing (fancy way of saying securing, sharing and storing data and sharing it). To this end, a lot and I mean a lot of data sets are publicly available.

- [Baidu Research](https://ai.baidu.com/broad/introduction?dataset=dureader){target="_blank"} - Baidu provides a wide range of data sets at no cost for research and personal uses. They provide data from the various business units like automated car testing, medical, video highlight. While it is unlikely you'll locate a survey response set, this is a good thing to note.

- [data.gov](https://www.data.gov/){target="_blank"} - In the United States, all publicly funded data sets are available barring those that may pose a security threat (but you can even get those eventually using the [Freedom of Information Act](https://www.foia.gov/data.html){target="_blank"}). Other bodies freely share their data as well such as the [UK](https://data.gov.uk/){target="_blank"}, the [EU](https://data.europa.eu/euodp/en/data/){target="_blank"}, and [India](https://data.gov.in/){target="_blank"}. There are plenty of other organizations that share their data too. For example, whatever your opinion is on the [World Bank](https://data.worldbank.org/){target="_blank"}or even if you don't have one, even they shares their data since it is publicly funded as well!

- [data.world](https://data.world/){target="_blank"} - One of the best publicly available repos out there. Some of the sets even come with full R scripts! Other software scripts like Excel, Python, SPSS, SAS, etc are available as well. This is strictly user driven so availability is contingent on who shares what and how.

- Github - Not only are public data sets plentiful on Github, but people have also taken the time to compile a list for the rest of us. Here are a few popular ones (I promise not every repo is named awesome on Github):
  - [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets){target="_blank"}
  - [Awesome Data](https://github.com/viisar/awesome-datasets){target="_blank"} <br><br>

- [Google Dataset Search](https://toolbox.google.com/datasetsearch){target="_blank"} - Much like nearly every other Google service (e.g. [Google Scholar](https://scholar.google.com/){target="_blank"}), Goggle Datasets doesn't actually house anything, rather it is a means for you to get to data, aka a portal what a fantastic name), without having to search all over the web. It is fairly new and their database grows every second - actually its faster than that but as humans we have trouble compartmentalizing any unit of time smaller than a second. Now if you've heard the term *indexing*, that is not this. The best analogy I can think of is creating a grocery shopping list as needed through the week (aka adding to the data base) and then reordering and grouping food items that are closest in proximity to each other so that you can get out of the store as quick and efficiently as possible^[Try doing this if you don't like shopping!]. 
  
- [Kaggle](https://www.kaggle.com){target="_blank"} - Described as an AirBnB for data scientists, this site has a ton of public and sometimes private data that has been cleared for public consumption. More than that, it is an absolute playpen if you like exploring data. If you go headfirst into a data set and cannot and I mean cannot cognitively picture an end goal or what the data will tell you until something is done with it, this is the place for you! 
  

### What to Turn in

After you have located a data set, do the data scientist thing and please follow these steps:

1. Open up the codebook and locate multiple columns:
  - one that has a unique identifier
  - multiple with quantiative data that have relationships or are being used to assess the same measure^[None should be filled with demographical information.]
  
2. Use the same steps outlined in the example piece to conduct your own principal component analysis. 

3. Answer the following questions on a word document. As usual, please put your name in the upper left hand corner.
  a. What is the official name of the data set you chose?
  b. What repository did you get it from (e.g. data.world, Kaggle, etc)? If you did not get it from a place where data is housed, please copy and paste the web address. Please do not copy and paste any additional nonsense that say search engines put on a web address. For example, if you've ever copied and pasted a website after using Google, you may notice that the address is obnoxiously long. I don't want that. If you are having trouble, contact me and I'll help you through it.
  c. How did you determine the number of components?
  d. What do the components tell you? *hint: look at the loadings*
  e. Describe the results into a single paragraph narrative. Try to be specific and concise. There is a very narrow way to interpret the results of a PCA.
  
4. Submit your script, a copy of the data set and responses on [eCampus](https://ecampus.wvu.edu/){target="_blank"}.

:::
