---
title: "Ordering Questions and Testing for Question Order Effects"
linktitle: "Week 7: Ordering Questions and Testing for Question Order Effects"
output:
  blogdown::html_page:
    toc: true
menu:
  assignment:
    parent: Pilot Study Review
    weight: 3
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

### Pilot Study Ledger
In this class, you will plan, create, **pilot**, administer, and analyze a survey from start to finish. After receiving a thumbs up from your planning task, in this second step you will create a draft survey that will eventually be administered in one form or another to your approved population.

#### Process
You may begin the pilot process as soon as you read this. Please be aware that the minimum standard for a pilot study are two iterations. If you wish to do less, then a discussion is warranted and you must provide a sufficient case. Please schedule an appointment to be taken place no later than **October 7** by **5:00 PM**.

#### Submit
There is one submission for this task: A csv or excel document outlining the history of your changes and submitted to [eCampus](https://ecampus.wvu.edu/){target="_blank"} by **October 11** by **11:59 PM**. You must account for every item within your survey in the order they appear in your online variant. This includes, but is not limited to the landing and gratitude pages. Please use the documents below to keep an accurate record as you will be using it to create a *skeleton* of your survey. 

- [pilot_ledger.csv](/files/Week 7/pilot_ledger.csv)
- [pilot_ledger_codebook.csv](/files/Week 7/pilot_ledger.csv)

:::
