---
title: "Time to Evaluate"
linktitle: "Week 11: Time to Evaluate"
output:
  rmarkdown::html_document
menu:
  extras:
    parent: Extras
    weight: 11
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

`r blogdown::shortcode("aes-header")`

```{r load_packages, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(fontawesome)
library(knitr)
library(kableExtra)
```

`r blogdown::shortcode("aes-header")`

## Evaluation Phase

We are currently in the evaluation process phase. This involves

```{r echo = FALSE}

unchecked <- as.character(fontawesome::fa("circle", fill = "#e4e4e4", height = "15px"))

checked <- as.character(fontawesome::fa("check-circle", fill = "#428bca", height = "15px"))

process <- tibble(
  
  phase = c("Process"),
  
  task = c("Administering an evaluation"),
  
  current <- c(checked)
  
)

```

<center>
```{r message=FALSE, warning=FALSE, eval = TRUE, echo = FALSE}
  process %>%
  kbl(escape = FALSE,
      align = 'llc') %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "20em") %>% 
  row_spec(0:1, extra_css = 'vertical-align: middle !important;', color = "#f7f7f7", background = "transparent")
```
</center>
