<!DOCTYPE html>
<html lang="en-us"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="https://www.facebook.com/2008/fbml">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Dr. Abhik Roy">

  
  
  
    
  
  <meta name="description" content="Introduction Preparation Sentiment Analysis Learning by Doing Extra Information Getting Data  Data Wrangling Exploring Data Lemmatize Words Using Stop Words Descriptive Statistics Wordclouds Bar Plots   Sentiment Analysis Basic Text Analysis Most Common Positive and Negative Words in a Bar Graph Most Common Positive and Negative Words in a WordCloud Positive and Negative Words in a Line Graph Positive and Negative Words in a Boxplot  Viewing Across all Lexicons    Introduction Preparation Download a script file of just the R chunks used in this walkthrough.">

  
  <link rel="alternate" hreflang="en-us" href="/lesson/sentimentanalysisintro/">

  


  
  
  
  <meta name="theme-color" content="#4974a5">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,400i,700,700i%7COverpass:400,400i,700,700i&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_huabb7f9a97b9bb4abf1475269d849d021_32197_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_huabb7f9a97b9bb4abf1475269d849d021_32197_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/lesson/sentimentanalysisintro/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@piechartssuck">
  <meta property="twitter:creator" content="@piechartssuck">
  
  <meta property="og:site_name" content="Statistical Methods I">
  <meta property="og:url" content="/lesson/sentimentanalysisintro/">
  <meta property="og:title" content="Week 15: Something Fun - An Introduction to Sentiment Analysis Using (My Favorite Band): The Grateful Dead | Statistical Methods I">
  <meta property="og:description" content="Introduction Preparation Sentiment Analysis Learning by Doing Extra Information Getting Data  Data Wrangling Exploring Data Lemmatize Words Using Stop Words Descriptive Statistics Wordclouds Bar Plots   Sentiment Analysis Basic Text Analysis Most Common Positive and Negative Words in a Bar Graph Most Common Positive and Negative Words in a WordCloud Positive and Negative Words in a Line Graph Positive and Negative Words in a Boxplot  Viewing Across all Lexicons    Introduction Preparation Download a script file of just the R chunks used in this walkthrough."><meta property="og:image" content="/img/course_info.png">
  <meta property="twitter:image" content="/img/course_info.png"><meta property="og:locale" content="en-us">
  
    
    
  

  



  


  


  <script src="https://kit.fontawesome.com/7b58dd72e9.js" crossorigin="anonymous"></script>

<link rel="shortcut icon" href="/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/img/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/img/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/img/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/img/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/img/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/img/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="/img/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/img/favicon-16x16.png" sizes="16x16" />
  <meta name="application-name" content="EDP 613: Statistical Methods I" />
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="/img/mstile-144x144.png" />


  <title>Week 15: Something Fun - An Introduction to Sentiment Analysis Using (My Favorite Band): The Grateful Dead | Statistical Methods I</title>

</head>


<body id="top" data-spy="scroll" data-offset="70"
    data-target="#TableOfContents"
    >

    <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


    









<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Statistical Methods I</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Statistical Methods I</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/syllabus/"><span>Syllabus</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Schedule</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/readings/"><span>Readings</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link  active" href="/lesson/"><span>Lessons</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/example/"><span>Examples</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/assignment/"><span>Assignments</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/due/"><span>Due?</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/resource/"><span>Resources</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/professor/"><span>Professor</span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://2020edp619.slack.com" target="_blank" rel="noopener"><span><i class="fab fa-slack"></i></span></a>
        </li>

        
        

        

        
        
        
          
            
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="https://rstudio.cloud/" target="_blank" rel="noopener"><span><i class="fab fa-r-project"></i></span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


    

<div class="container-fluid docs">
    <div class="row flex-xl-nowrap">
        <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
            





  
    
  




<form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  

  
  
  
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/lesson/">Overview</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/lesson/">About the Lessons</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/lesson/01-lesson/">Lessons</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/lesson/01-lesson/">Week 1: The What and Why of Statistics</a>
      </li>
      
      <li >
        <a href="/lesson/02-lesson/">Week 2: The Organization and Graphic Presentation of Data</a>
      </li>
      
      <li >
        <a href="/lesson/03-lesson/">Week 3: Measures of Central Tendency</a>
      </li>
      
      <li >
        <a href="/lesson/04-lesson/">Week 4: Measures of Variability</a>
      </li>
      
      <li >
        <a href="/lesson/05-lesson/">Week 5: The Normal Distribution</a>
      </li>
      
      <li >
        <a href="/lesson/06-lesson/">Week 6: Sampling and Sampling Distributions</a>
      </li>
      
      <li >
        <a href="/lesson/07-lesson/">Week 7: Sampling and Sampling Distributions</a>
      </li>
      
      <li >
        <a href="/lesson/09-lesson/">Week 9: Estimations</a>
      </li>
      
      <li >
        <a href="/lesson/10-lesson/">Week 10: Testing Hypotheses</a>
      </li>
      
      <li >
        <a href="/lesson/11-lesson/">Week 11: Bivariate Tables</a>
      </li>
      
      <li >
        <a href="/lesson/12-lesson/">Week 12: The Chi-Square Test and Measures of Association</a>
      </li>
      
      <li >
        <a href="/lesson/13-lesson/">Week 13: Chi-Square and ANOVAs</a>
      </li>
      
      <li >
        <a href="/lesson/15-lesson/">Week 15: Sentiment Analysis</a>
      </li>
      
    </ul>
    

  </div>
  
  <div class="docs-toc-item">
    <a class="docs-toc-link" href="/lesson/nflpipes/">Walkthroughs</a>
    <ul class="nav docs-sidenav">
      
      <li >
        <a href="/lesson/nflpipes/">Week 5: Dplyr, Pipes, and the NFL</a>
      </li>
      
      <li >
        <a href="/lesson/hypotheses/">Week 10: The t-tests</a>
      </li>
      
      <li >
        <a href="/lesson/chisquare/">Week 12: Tidying Up the Chi Square Statistics</a>
      </li>
      
      <li class="active">
        <a href="/lesson/sentimentanalysisintro/">Week 15: Something Fun - An Introduction to Sentiment Analysis Using (My Favorite Band): The Grateful Dead</a>
      </li>
      
    </ul>
    

  </div>
  
  
</nav>

        </div>

        

        <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

            <article class="article">

                <div class="docs-article-container">
                    <h1>Week 15: Something Fun - An Introduction to Sentiment Analysis Using (My Favorite Band): The Grateful Dead</h1>

                    

                    

                    

                    <div class="article-style">
                        
<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />

<div id="TOC">
<ul>
<li><a href="#introduction">Introduction</a><ul>
<li><a href="#preparation">Preparation</a></li>
<li><a href="#sentiment-analysis">Sentiment Analysis</a></li>
<li><a href="#learning-by-doing">Learning by Doing</a></li>
<li><a href="#extra-information">Extra Information</a></li>
<li><a href="#getting-data">Getting Data</a></li>
</ul></li>
<li><a href="#data-wrangling">Data Wrangling</a><ul>
<li><a href="#exploring-data">Exploring Data</a></li>
<li><a href="#lemmatize-words">Lemmatize Words</a></li>
<li><a href="#using-stop-words">Using Stop Words</a></li>
<li><a href="#descriptive-statistics">Descriptive Statistics</a><ul>
<li><a href="#wordclouds">Wordclouds</a></li>
<li><a href="#bar-plots">Bar Plots</a></li>
</ul></li>
</ul></li>
<li><a href="#sentiment-analysis-1">Sentiment Analysis</a><ul>
<li><a href="#basic-text-analysis">Basic Text Analysis</a><ul>
<li><a href="#most-common-positive-and-negative-words-in-a-bar-graph">Most Common Positive and Negative Words in a Bar Graph</a></li>
<li><a href="#most-common-positive-and-negative-words-in-a-wordcloud">Most Common Positive and Negative Words in a WordCloud</a></li>
<li><a href="#positive-and-negative-words-in-a-line-graph">Positive and Negative Words in a Line Graph</a></li>
<li><a href="#positive-and-negative-words-in-a-boxplot">Positive and Negative Words in a Boxplot</a></li>
</ul></li>
<li><a href="#viewing-across-all-lexicons">Viewing Across all Lexicons</a></li>
</ul></li>
</ul>
</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<div id="preparation" class="section level2">
<h2>Preparation</h2>
<p>Download a <a href="/scripts/SentimentAnalysisIntro.R" target="_blank">script</a> file of just the R chunks used in this walkthrough.</p>
</div>
<div id="sentiment-analysis" class="section level2">
<h2>Sentiment Analysis</h2>
<p>Without getting into the specifics of machine learning, a <strong>sentiment analysis</strong> is a quantitative process of determining whether a piece of writing is positive, negative or neutral. It entails using a mix of statistics (you know…that old chestnut), <a href="https://www.sas.com/en_us/insights/analytics/what-is-natural-language-processing-nlp.html" target="_blank">natural language processing (NLP)</a>, and <a href="https://www.ibm.com/cloud/learn/machine-learning" target="_blank">machine learning</a> to identify and extract subjective information from text files, for instance, a reviewer’s feelings, thoughts, judgments, or assessments within open text. If you want to know more about this method, Qualtrics provides a nice readable <a href="https://www.qualtrics.com/experience-management/research/sentiment-analysis/" target="_blank">writeup</a> about it.</p>
</div>
<div id="learning-by-doing" class="section level2">
<h2>Learning by Doing</h2>
<p>We are essentially going to learn about a sentiment analysis using music…well music that I like anyway. In this session we’ll be looking at some Grateful Dead lyrics from two albums.</p>
<p>With that said, let’s load up some libraries. If you don’t have some of these (and you most likely don’t), remember to download them first using <code>Tools &gt; Install Packages</code>.</p>
<pre class="r"><code># We are using the tidyverse family which is essentially the gold standard for 
# data wrangling:
library(tidyverse) 
library(scales)

# text mining and annoying wordclouds based on the tidyverse family
library(tidytext)
library(ggwordcloud)
library(textstem)
library(textdata)
library(wordcloud)

# getting lyrics
library(genius) # Allows you to download lyrics for an entire album in a tidy format from
# genius.com

# the aesthetics
library(viridis)
library(RColorBrewer)
library(hrbrthemes)
hrbrthemes::import_roboto_condensed()</code></pre>
</div>
<div id="extra-information" class="section level2">
<h2>Extra Information</h2>
<p>More information about
* the <code>tidyverse</code> family of packages are introduced by selecting <a href="https://www.tidyverse.org/" target="_blank">https://www.tidyverse.org/</a>.</p>
<ul>
<li><p>genius.com can be found here <a href="https://genius.com/" target="_blank">https://genius.com/</a>.</p></li>
<li><p>the genius package can be found via this link
<a href="https://github.com/josiahparry/genius" target="_blank">https://github.com/josiahparry/genius</a>.</p></li>
</ul>
</div>
<div id="getting-data" class="section level2">
<h2>Getting Data</h2>
<p>Grab the lyrics for <strong><em>American Beauty</em></strong> (1971) which was more about rock and roll and <strong><em>Shakedown Street</em></strong> (1978) which was influenced by disco (ugh yes…disco). Were going to see if the sentiments associated within each album changed over time. On a side note, feel free to grab albums and lyrics that you like instead but the example will be based on the two albums so I would suggest going through it with these first and then doing your own. We’ll compare the two using a sentiment analysis.</p>
<pre class="r"><code>american_beauty &lt;- genius_album(artist = &quot;The Grateful Dead&quot;, album = &quot;***American Beauty***&quot;)</code></pre>
<pre><code>## Joining, by = c(&quot;album_name&quot;, &quot;track_n&quot;, &quot;track_url&quot;)</code></pre>
<p>To see the results, just type in the following:</p>
<pre class="r"><code>american_beauty</code></pre>
<pre><code>## # A tibble: 359 x 4
##    track_n  line lyric                                               track_title
##      &lt;int&gt; &lt;int&gt; &lt;chr&gt;                                               &lt;chr&gt;      
##  1       1     1 Look out of any window                              Box of Rain
##  2       1     2 Any morning, any evening, any day                   Box of Rain
##  3       1     3 Maybe the sun is shining                            Box of Rain
##  4       1     4 Birds are winging or rain is falling from a heavy … Box of Rain
##  5       1     5 What do you want me to do                           Box of Rain
##  6       1     6 To do for you to see you through?                   Box of Rain
##  7       1     7 For this is all a dream we dreamed                  Box of Rain
##  8       1     8 One afternoon, long ago                             Box of Rain
##  9       1     9 Walk out of any doorway                             Box of Rain
## 10       1    10 Feel your way, feel your way like the day before    Box of Rain
## # … with 349 more rows</code></pre>
<p>Now let’s do the same for <strong><em>Shakedown Street</em></strong></p>
<pre class="r"><code>shakedown_street &lt;- genius_album(artist = &quot;The Grateful Dead&quot;, album = &quot;***Shakedown Street***&quot;)</code></pre>
<pre><code>## Joining, by = c(&quot;album_name&quot;, &quot;track_n&quot;, &quot;track_url&quot;)</code></pre>
<p>And the results look like:</p>
<pre class="r"><code>shakedown_street</code></pre>
<pre><code>## # A tibble: 304 x 4
##    track_n  line lyric                                               track_title
##      &lt;int&gt; &lt;int&gt; &lt;chr&gt;                                               &lt;chr&gt;      
##  1       1     1 &quot;Well, I was feeling so bad, asked my family docto… Good Lovin&#39;
##  2       1     2 &quot;I said, \&quot;Doctor, Doctor, Mister M.D., (doctor) c… Good Lovin&#39;
##  3       1     3 &quot;He said, \&quot;Yeah, yeah, yeah, yeah, yeah, yeah, ye… Good Lovin&#39;
##  4       1     4 &quot;All you need, all you really need: good loving&quot;    Good Lovin&#39;
##  5       1     5 &quot;Because you got to have loving (good loving)&quot;      Good Lovin&#39;
##  6       1     6 &quot;Everybody got to have loving (good loving)&quot;        Good Lovin&#39;
##  7       1     7 &quot;A little good loving now baby, good loving&quot;        Good Lovin&#39;
##  8       1     8 &quot;So come on baby, squeeze me tight&quot;                 Good Lovin&#39;
##  9       1     9 &quot;Don&#39;t you want your daddy to be alright?&quot;          Good Lovin&#39;
## 10       1    10 &quot;I said baby, now it&#39;s for sure&quot;                    Good Lovin&#39;
## # … with 294 more rows</code></pre>
<p>To find out the internal structure of one of your data sets, run this:</p>
<pre class="r"><code>str(shakedown_street)</code></pre>
<pre><code>## tibble [304 × 4] (S3: tbl_df/tbl/data.frame)
##  $ track_n    : int [1:304] 1 1 1 1 1 1 1 1 1 1 ...
##  $ line       : int [1:304] 1 2 3 4 5 6 7 8 9 10 ...
##  $ lyric      : chr [1:304] &quot;Well, I was feeling so bad, asked my family doctor about what I had&quot; &quot;I said, \&quot;Doctor, Doctor, Mister M.D., (doctor) can you tell me (doctor), what&#39;s ailing me? (doctor)\&quot;&quot; &quot;He said, \&quot;Yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah, yeah\&quot;&quot; &quot;All you need, all you really need: good loving&quot; ...
##  $ track_title: chr [1:304] &quot;Good Lovin&#39;&quot; &quot;Good Lovin&#39;&quot; &quot;Good Lovin&#39;&quot; &quot;Good Lovin&#39;&quot; ...</code></pre>
<p>This gives you a good bit of information about the structure of your data set.
* The class of the data are in multiple formats: <code>tbl_df</code> (tabular data frame), <code>tbl</code> (table), and <code>data.frame</code> (normal data frame). This implies that you can use common commands to wrangle the data within this variable.</p>
<ul>
<li><p>You have four (4) internal variables and 304 lines in this data frame (think an excel document which has 4 columns and 304 rows).</p></li>
<li><p>Notice that the track_title (track title) and <code>lyric</code> (lyrics) columns are character vectors while <code>track_n</code> (track number) and <code>line</code> (line number) are integer vectors. These are important because what you can do with any vector is mostly dependent on its type.</p></li>
</ul>
</div>
</div>
<div id="data-wrangling" class="section level1">
<h1>Data Wrangling</h1>
<p>If we’re going to compare the two albums, we should probably put them in the same data frame. But to make sure we can distinguish each, we’re going to have to tag them by album name. To do this, we need to add a column. The package <code>dplyr</code> let’s you mess around with the data without destroying the data frame format. It also lets you deal with pipes (<code>%&gt;%</code>) which is a fantastic thing. During the dark days of R before pipes, you had to go back and rerun any R code that you made changes to which meant you had to keep track of everything. In any case, when using pipes, to do (nearly) anything to the data frame, you must use the command <code>mutate</code>.</p>
<p>Remember we are adding a column that denoted the album name:</p>
<pre class="r"><code>american_beauty_tagged &lt;- american_beauty %&gt;% 
  mutate(album = &quot;***American Beauty***&quot;) %&gt;%
  select(album, track_title, track_n, line, lyric)</code></pre>
<br>
<hr>
<p><br></p>
<p>Ok so let’s take a moment to get our bearings straight. Currently we are</p>
<ol style="list-style-type: decimal">
<li><p>using the <code>american_beauty</code> data set</p></li>
<li><p>adding a column named album and then populating it with the text <strong><em>American Beauty</em></strong> (in quotes); and</p></li>
<li><p>rearranging the columns. By default, any new columns are put at the end of a data frame. Just to satisfy my obsessive nature, we’ll rearrange them in order of scope by putting the album name in front.</p></li>
</ol>
<br>
<hr>
<p><br></p>
<p>Good? Ok then let’s take a look at the data set now:</p>
<pre class="r"><code>american_beauty</code></pre>
<pre><code>## # A tibble: 359 x 4
##    track_n  line lyric                                               track_title
##      &lt;int&gt; &lt;int&gt; &lt;chr&gt;                                               &lt;chr&gt;      
##  1       1     1 Look out of any window                              Box of Rain
##  2       1     2 Any morning, any evening, any day                   Box of Rain
##  3       1     3 Maybe the sun is shining                            Box of Rain
##  4       1     4 Birds are winging or rain is falling from a heavy … Box of Rain
##  5       1     5 What do you want me to do                           Box of Rain
##  6       1     6 To do for you to see you through?                   Box of Rain
##  7       1     7 For this is all a dream we dreamed                  Box of Rain
##  8       1     8 One afternoon, long ago                             Box of Rain
##  9       1     9 Walk out of any doorway                             Box of Rain
## 10       1    10 Feel your way, feel your way like the day before    Box of Rain
## # … with 349 more rows</code></pre>
<p>Sure enough, there’s the column with the album name. So now let’s do the same for the other album</p>
<pre class="r"><code>shakedown_street_tagged &lt;- shakedown_street %&gt;% 
  mutate(album = &quot;***Shakedown Street***&quot;) %&gt;%
  select(album, track_title, track_n, line, lyric)</code></pre>
<p>and verify:</p>
<pre class="r"><code>shakedown_street</code></pre>
<pre><code>## # A tibble: 304 x 4
##    track_n  line lyric                                               track_title
##      &lt;int&gt; &lt;int&gt; &lt;chr&gt;                                               &lt;chr&gt;      
##  1       1     1 &quot;Well, I was feeling so bad, asked my family docto… Good Lovin&#39;
##  2       1     2 &quot;I said, \&quot;Doctor, Doctor, Mister M.D., (doctor) c… Good Lovin&#39;
##  3       1     3 &quot;He said, \&quot;Yeah, yeah, yeah, yeah, yeah, yeah, ye… Good Lovin&#39;
##  4       1     4 &quot;All you need, all you really need: good loving&quot;    Good Lovin&#39;
##  5       1     5 &quot;Because you got to have loving (good loving)&quot;      Good Lovin&#39;
##  6       1     6 &quot;Everybody got to have loving (good loving)&quot;        Good Lovin&#39;
##  7       1     7 &quot;A little good loving now baby, good loving&quot;        Good Lovin&#39;
##  8       1     8 &quot;So come on baby, squeeze me tight&quot;                 Good Lovin&#39;
##  9       1     9 &quot;Don&#39;t you want your daddy to be alright?&quot;          Good Lovin&#39;
## 10       1    10 &quot;I said baby, now it&#39;s for sure&quot;                    Good Lovin&#39;
## # … with 294 more rows</code></pre>
<p>Great those look good. Now to merge the data sets, we are going to use a command called <code>rbind</code>. The single requirement is that both data frames have the same column names since it needs to know what columns go with what (but notice that having the same column names implies that the columns do not have to be in the same order!)</p>
<pre class="r"><code>all_albums &lt;- rbind(american_beauty_tagged, shakedown_street_tagged)</code></pre>
<p>If you simply do the following</p>
<pre class="r"><code>all_albums</code></pre>
<pre><code>## # A tibble: 663 x 5
##    album           track_title track_n  line lyric                              
##    &lt;chr&gt;           &lt;chr&gt;         &lt;int&gt; &lt;int&gt; &lt;chr&gt;                              
##  1 ***American Be… Box of Rain       1     1 Look out of any window             
##  2 ***American Be… Box of Rain       1     2 Any morning, any evening, any day  
##  3 ***American Be… Box of Rain       1     3 Maybe the sun is shining           
##  4 ***American Be… Box of Rain       1     4 Birds are winging or rain is falli…
##  5 ***American Be… Box of Rain       1     5 What do you want me to do          
##  6 ***American Be… Box of Rain       1     6 To do for you to see you through?  
##  7 ***American Be… Box of Rain       1     7 For this is all a dream we dreamed 
##  8 ***American Be… Box of Rain       1     8 One afternoon, long ago            
##  9 ***American Be… Box of Rain       1     9 Walk out of any doorway            
## 10 ***American Be… Box of Rain       1    10 Feel your way, feel your way like …
## # … with 653 more rows</code></pre>
<p>Notice that you can’t actually observe both data frames were <em>stacked</em>, or <em>bound.</em> To do this, or at least get an indicator that the binding worked, you can find the <em>unique</em> values in a column by doing</p>
<pre class="r"><code>unique(all_albums$album)</code></pre>
<pre><code>## [1] &quot;***American Beauty***&quot;  &quot;***Shakedown Street***&quot;</code></pre>
<p>Sure enough, it looks like both albums are there.</p>
<div id="exploring-data" class="section level2">
<h2>Exploring Data</h2>
<p>OK now to do some exploratory data analysis (EDA) which have to be displayed in a useless format on par with <em>pie charts</em> - that is <em>wordclouds</em>. Let’s tidy the data sets.</p>
<p>First we are going to tokenize the lyrics into a tidy dataframe</p>
<pre class="r"><code>tidy_lyrics&lt;- all_albums %&gt;% 
  group_by(album) %&gt;% 
  unnest_tokens(word, lyric) </code></pre>
<p>So here we are
1. using the all_albums data set we just created;</p>
<ol start="2" style="list-style-type: decimal">
<li><p>grouping by album name which means all operations are done within the context of each album; and</p></li>
<li><p>tokenizing the data set which basically is a fancy way of saying we’re splitting up lyrics into words within each album.</p></li>
</ol>
<p>Take a look at what this data frame now looks like by using</p>
<pre class="r"><code>tidy_lyrics %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 5
## # Groups:   album [1]
##   album                 track_title track_n  line word  
##   &lt;chr&gt;                 &lt;chr&gt;         &lt;int&gt; &lt;int&gt; &lt;chr&gt; 
## 1 ***American Beauty*** Box of Rain       1     1 look  
## 2 ***American Beauty*** Box of Rain       1     1 out   
## 3 ***American Beauty*** Box of Rain       1     1 of    
## 4 ***American Beauty*** Box of Rain       1     1 any   
## 5 ***American Beauty*** Box of Rain       1     1 window
## 6 ***American Beauty*** Box of Rain       1     2 any</code></pre>
<p>Or simply use <code>View(tidy_lyrics)</code> to get a full view in a separate tab.</p>
</div>
<div id="lemmatize-words" class="section level2">
<h2>Lemmatize Words</h2>
<p>For grammatical reasons, lyrics are going to use different forms of a word known as <a href="https://essentialsoflinguistics.pressbooks.com/chapter/6-5-unsure-how-to-format-that-derivational-morphology/" target="_blank">morphological derivations</a> such as drink, drinks, and drinking to name a few. Additionally, there are families of derivationally related words with similar meanings known as differentiated inflections such as democracy, democratic, and democratization. In many situations including lyrics, it is useful to use the basic term for each of these variants. For this we have <strong>stemming</strong> and <strong>lemmatization</strong>.</p>
<ul>
<li><p><strong>Stemming</strong> refers to a crude heuristic process that chops off the ends of words in the hope of achieving this goal correctly most of the time, and often includes the removal of derivational affixes.</p></li>
<li><p><strong>Lemmatization</strong> refers to doing things properly with the use of a vocabulary and morphological analysis of words, normally aiming to remove inflectional endings only and to return the base or dictionary form of a word, which is known as the lemma.</p></li>
</ul>
<p>The <code>textstem</code> package can do both, but for reasons associated with robustness, we’ll use lemmatization.</p>
<pre class="r"><code>tidy_lyrics$word &lt;- lemmatize_words(tidy_lyrics$word)</code></pre>
<p>The command (right) above takes the column <code>word</code> in <code>tidy_lyrics</code>, lemmatizes it, and then replaces the column <code>word</code> in <code>tidy_lyrics</code> (left) with the results. Take a look using <code>View(tidy_lyrics)</code>.</p>
</div>
<div id="using-stop-words" class="section level2">
<h2>Using Stop Words</h2>
<p>Now that we have a list in a tidy format, let’s do something with it. First let’s remove all of the stop words. Recall that these are terms that are commonly used (e.g. the, an, in, etc) and for this type of analysis, are noise and basically useless. To do this, we’re going to use some logic! The approach that is the most efficient besides making someone else do it is to utilize <em>joins</em>. If you want to know more about joins in R - which you definitely should get familiar with as it will make merging of data sets so much easier in your life - check out <a href="https://stat545.com/bit001_dplyr-cheatsheet.html" target="_blank">Dr. Jenny Bryant’s Stat545 course</a>.</p>
<p>In our case, we’ll be using an <code>anti_join</code> which basically gives you an output by finding the rows of the first table cannot that cannot be matched in the second table. But before that, let’s pull out the stop words from the <code>tidytext</code> package by doing</p>
<pre class="r"><code>data(&quot;stop_words&quot;)</code></pre>
<p>and then we’ll remove those words from our tidy data frame using an <code>anti_join</code></p>
<pre class="r"><code>tidy_lyrics_nsw &lt;- tidy_lyrics %&gt;%
  ungroup() %&gt;%
  anti_join(stop_words)</code></pre>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<br>
<hr>
<p><br></p>
<p>Ok so let’s take another moment to get our bearings straight. Currently we are</p>
<ol style="list-style-type: decimal">
<li><p>using the <code>tidy_lyrics</code> data set that we created;</p></li>
<li><p>ungrouping the data set; and</p></li>
<li><p>removing all of the stop words from that data frame.</p></li>
</ol>
<br>
<hr>
<p><br></p>
<p>Now you can take a look by using <code>View(tidy_lyrics_nsw)</code> or just look at the top six using the following syntax</p>
<pre class="r"><code>tidy_lyrics_nsw %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 x 5
##   album                 track_title track_n  line word   
##   &lt;chr&gt;                 &lt;chr&gt;         &lt;int&gt; &lt;int&gt; &lt;chr&gt;  
## 1 ***American Beauty*** Box of Rain       1     1 window 
## 2 ***American Beauty*** Box of Rain       1     2 morning
## 3 ***American Beauty*** Box of Rain       1     2 day    
## 4 ***American Beauty*** Box of Rain       1     3 sun    
## 5 ***American Beauty*** Box of Rain       1     3 shine  
## 6 ***American Beauty*** Box of Rain       1     4 bird</code></pre>
<div style="page-break-after: always;"></div>
<p>Not seeing what you want? How about the bottom six then?</p>
<pre class="r"><code>tidy_lyrics_nsw %&gt;%
  tail()</code></pre>
<pre><code>## # A tibble: 6 x 5
##   album                  track_title        track_n  line word   
##   &lt;chr&gt;                  &lt;chr&gt;                &lt;int&gt; &lt;int&gt; &lt;chr&gt;  
## 1 ***Shakedown Street*** Stagger Lee (Live)      14    29 lee    
## 2 ***Shakedown Street*** Stagger Lee (Live)      14    30 song   
## 3 ***Shakedown Street*** Stagger Lee (Live)      14    30 delia  
## 4 ***Shakedown Street*** Stagger Lee (Live)      14    30 sing   
## 5 ***Shakedown Street*** Stagger Lee (Live)      14    30 stagger
## 6 ***Shakedown Street*** Stagger Lee (Live)      14    30 lee</code></pre>
<p>We can remove additional words manually but for the purposes of this walkthrough, let’s not.</p>
</div>
<div id="descriptive-statistics" class="section level2">
<h2>Descriptive Statistics</h2>
<p>Until recently, the quantitative approach to analyze open text was in the use of word clouds. For all of my griping, this isn’t necessarily a flawed approach since it will indicate if some words are more important than others but they are <em>descriptive</em> at best. Historically, the issue has been related to certain scholars making overarching claims, or <em>inferences</em> from what are essentially visual representations of frequency counts which you should know by now is nonsense. However, with the advent of machine learning as a methodological tool, we now use inferential statistics to derive usable outcomes though there are still some people who stick by frequencies. In any case, let’s calculate some frequencies to get an idea of how our data looks.</p>
<pre class="r"><code>frequencies_lyrics &lt;- tidy_lyrics_nsw %&gt;%
  group_by(album) %&gt;%
  count(word, sort = TRUE)</code></pre>
<p>and then plot them on a wordcloud. At this point, if you are unfamiliar or uncomfortable with <code>ggplot</code>, I suggest going through or reviewing the first <code>ggplot</code> section on <a href="https://www.datacamp.com/" target="_blank">datacamp</a>. With that said, there will also be a brief explanation below of what’s used below the plot.</p>
<p>OK if you’re ready, run the following but be forewarned, it may take some time!</p>
<div id="wordclouds" class="section level3">
<h3>Wordclouds</h3>
<pre class="r"><code>set.seed(99)
ggplot(frequencies_lyrics, aes(label = word, size = n, color = album)) +
  geom_text_wordcloud() +
  scale_radius(range = c(0, 20)) +
  theme_minimal()</code></pre>
<pre><code>## Warning: Removed 2 rows containing missing values (geom_text_wordcloud).</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/wordcloud-1.png" width="672" /></p>
<p>So what’s going on above? Well let’s break it down:</p>
<ol style="list-style-type: decimal">
<li><p><code>ggplot(frequencies_lyrics, aes(label = word, size = n, color = album))</code> tells R to use the <code>ggplot2</code> package by looking at the data set <code>frequencies_lyrics</code> with the aesthetics (<code>aes</code>) of labeling the data by the word, sizing each by its corresponding frequency (<code>n</code>), and color by album title (<code>album</code>).</p></li>
<li><p><code>geom_text_wordcloud()</code> tells R to use the <code>ggwordcloud</code> package and that text will be used to represent the data and to put it in a spiral.</p></li>
<li><p><code>scale_radius(range = c(0, 20))</code> tells <code>ggplot</code> that the smallest a data point can be is 0 points and the largest is 20 points.</p></li>
<li><p><code>theme_minimal</code> is a <code>ggplot</code> theme that removes all default(background, axes, etc.) information and just plots what you ask for.</p></li>
</ol>
<p>You may notice that I did not go over <code>set.seed</code>. That is for another time because it deals with probabilities that are contingent on how data is analyzed and/or rendered by each package in R.</p>
<p>OK great but that takes too long to render, its not very pretty nor does it do a great job of splitting the words apart - we do want to compare them after all! Let’s make it better:</p>
<pre class="r"><code>set.seed(99)
frequencies_lyrics %&gt;%
  filter(n &gt; 1) %&gt;%
  ggplot(aes(label = word, size = n, color = album)) +
  scale_color_manual(values = c(&quot;#5bc0de&quot;, &quot;#5cb85c&quot;)) +
  geom_text_wordcloud(rm_outside = TRUE, shape = &quot;circle&quot;) +
  scale_radius(range = c(4, 15)) +
  theme_minimal() +
  facet_grid(.~ album) +
  theme(panel.spacing = unit(0.5, &quot;cm&quot;))</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_text_wordcloud).</code></pre>
<pre><code>## Some words could not fit on page. They have been removed.
## Some words could not fit on page. They have been removed.</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/wordcloud_custom_actual-1.png" width="672" /></p>
<p>That looks better and we know what words come from what album. So what’s different here?
Well first of all, it is worth noting that not all of the syntax from above will be explained here simply due to the fact they are included for aesthetics and have nothing to do with the function creating the actual wordcloud. However, you are given the entire code so that the modified output is or will be at some point understandable. If you would like to know what this looks like without the extra aesthetics for comparison, run the following in your companion R script:</p>
<pre class="r"><code>set.seed(99)
frequencies_lyrics %&gt;%
  filter(n &gt; 1) %&gt;%
ggplot(aes(label = word, size = n, color = album)) +
  scale_color_manual(values = c(&quot;#5bc0de&quot;, &quot;#5cb85c&quot;)) +
  geom_text_wordcloud(rm_outside = TRUE, shape = &quot;circle&quot;) +
  scale_radius(range = c(4, 15)) +
  theme_minimal() +
  facet_grid(album ~ .)</code></pre>
<p>Now back to the pending question that has been updated a bit: <em>What are the major differences here that aren’t related to the aesthetics?</em></p>
<ol style="list-style-type: decimal">
<li>If you call <code>frequencies_lyrics</code>, you’ll notice that there are 684 rows implying that R has to plot 684 words. That takes some time! To reduce the time and before even calling <code>ggplot</code>, let’s get rid of the “one offs”, or those terms that only appear once. Here we</li>
</ol>
<ul>
<li><p>called the original data set,</p></li>
<li><p>filtered the frequency <code>n</code> by telling R to only look at values greater than 1, and</p></li>
<li><p>then called <code>ggplot</code>. One side note, notice that we don’t called the data set again in <code>ggplot</code> since we already did that when filtering. The <code>%&gt;%</code> gives you the control to pass information through pipes. Much like anything Mario…pipes make everything better.</p></li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><p>I have manually assigned colors by using the <code>scale_color_manual</code> command and inputting hexadecimal, or hex codes. These are one of two ways internet browsers determine what colors you see on screen (the other is called RBG) and most computer languages recognize them too. You can Google hex codes and find all sorts of examples. I suggest using this site which also includes user generated palettes, but obviously there is no mandate: <a href="https://www.color-hex.com/" target="_blank">https://www.color-hex.com/</a>.</p></li>
<li><p>(same as before)</p></li>
<li><p>To make some of the text appear readable, the range of <code>scale_radius</code> was changed to reflect a minimum of 2 points.</p></li>
<li><p>(same as before)</p></li>
<li><p><code>facet_grid</code> (and its counterpart <code>facet_wrap</code> - not shown here) is a way of splitting up a visualization by a value in a column within your data frame. If you were confused as to why the album name was important and that we binded the original data frames, this is the reason! There are ways to customize a facet but we’ll get to that later.</p></li>
</ol>
<p><em>NOTE: If you see some blurred or overlapping text, just push the Zoom option right above the graphics window.</em></p>
<p>You can find more information, examples, and usable syntax/lines of code for <code>ggwordcloud</code> by selecting going to this <a href="https://cran.r-project.org/web/packages/ggwordcloud/vignettes/ggwordcloud.html" target="_blank">vignette</a>.</p>
</div>
<div id="bar-plots" class="section level3">
<h3>Bar Plots</h3>
<p>One avenue to look at when comparing sets of open ended text is to compare terms, in that are common terms used? We can do this or <a href="https://www.youtube.com/watch?v=AjPau5QYtYs" target="_blank">we can dance if we want to</a>. Let’s say we don’t do the latter:</p>
<pre class="r"><code>frequencies_lyrics %&gt;%
  filter(n &gt; 5) %&gt;%
  group_by(album) %&gt;% 
  count(word, sort = TRUE) %&gt;%
  mutate(word = reorder(word, n)) %&gt;% 
  ungroup() %&gt;% 
  mutate(album = reorder(album, n)) %&gt;% 
  ggplot(aes(word, n)) +
  geom_bar(stat = &quot;identity&quot;) +
  facet_grid(~ album) +
  xlab(NULL) +
  coord_flip() +
  theme(axis.text.y = element_text(size = 8))</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/frequency_by_facet-1.png" width="672" /></p>
<p>There is a lot going on here! While some of these items may be repetitive, let’s break it down anyway:</p>
<ol style="list-style-type: decimal">
<li><p>The <code>frequencies_lyrics</code> data set has been called.</p></li>
<li><p>We use <code>filter(n &gt; 5)</code> to filter out all of the word counts that are 5 or less. If you are using your own data set, this will vary.</p></li>
<li><p>Since we are looking at albums, we should first pair those out by using <code>group_by(album)</code>.</p></li>
<li><p>Using <code>count(word, sort = TRUE)</code>, we count the number of words. Now you may be saying something like “Wait! didn’t we already do that?” Well we did but we counted them across both albums basically ignoring which word came from what album. This time, when we used <code>group_by(album)</code>, the system now performs all operations by album. So words are now counted within each album.</p></li>
<li><p>If you run the entire pipe chain up to this <code>count(word, sort = TRUE)</code>, you may have noticed that the words are in order by counts. We can reorder the column <code>word</code> by a particular word and then their respective counts <code>n</code> by using <code>mutate(word = reorder(word, n))</code>.</p></li>
<li><p>When you group something, that structure is maintained indefinitely. To remove it, we use the common <code>ungroup()</code>.</p></li>
<li><p>Similar to step 5, we can reorder the column <code>album</code> by a particular album and then their respective counts <code>n</code> by using <code>mutate(album = reorder(album, n))</code>.</p></li>
</ol>
<p>At this point, you may realize we are starting to plot. The great thing about the tidyverse universe is that you can do operations and plot in one fell swoop.</p>
<ol start="8" style="list-style-type: decimal">
<li><p><code>ggplot(aes(word, n))</code> tells R that we’re going to plot something using ggplot using the a <code>word</code> on the <em>x</em>-axis and its corresponding count <code>n</code> on the y-axis.</p></li>
<li><p><code>geom_bar(stat = "identity")</code> indicates that we are going to use as bar plot. For the time being, we won’t discuss the <code>stat = identity</code> part except to tell you that when a <em>y</em> variable is declared, <code>geom_bar</code> requires <code>stat = identity</code>.</p></li>
<li><p><code>facet_grid(~ albums)</code> simply means we are going to facet, or ploy by albums.</p></li>
<li><p><code>xlab(NULL)</code> tells the system to ignore the label on the <em>x</em>-axis which in this case is word.</p></li>
<li><p>Running the command up to this point yields vertical bar plots which are somewhat difficult to compare. They would probably be easier to interpret if the bars were horizontal. Well <code>coord_flip()</code> does just that! This flips the <em>x</em>- and <em>y</em>-axes as well.</p></li>
<li><p>We will discuss themes at a later point but so you can simply read the vertical axis with the words, we are going to make the font size 8 (pixels) by stating <code>theme(axis.text.y = element_text(size = 8))</code>.</p></li>
</ol>
</div>
</div>
</div>
<div id="sentiment-analysis-1" class="section level1">
<h1>Sentiment Analysis</h1>
<p>Now we’ll investigate the various sentiments and emotions expressed in the lyrics by using three sentiment dictionaries or <strong>lexicons</strong>, included with the <code>tidytext</code> package: <strong>Bing</strong>, <strong>NRC</strong>, and <strong>AFINN</strong>. I won’t cover what these are in great depth but in a nutshell</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
lexicon
</th>
<th style="text-align:left;">
description
</th>
<th style="text-align:left;">
variable type
</th>
<th style="text-align:center;">
sentiments
</th>
<th style="text-align:left;">
more information
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Bing
</td>
<td style="text-align:left;">
A backend of <a href="https://www.bing.com/" target="_blank">Microsoft Bing</a>), this lexicon may be used to assesses open text for its polarities in sentiments.
</td>
<td style="text-align:left;">
categorical
</td>
<td style="text-align:center;">
positive, negative
</td>
<td style="text-align:left;">
<a href="https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html" target="_blank">Bing</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
NRC
</td>
<td style="text-align:left;">
One of the most utilized and researched lexicons that provides information about emotional context.
</td>
<td style="text-align:left;">
categorical
</td>
<td style="text-align:center;">
anger, anticipation, disgust, fear, joy, sadness, surprise, trust
</td>
<td style="text-align:left;">
<a href="https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm" target="_blank">NRC</a>
</td>
</tr>
<tr>
<td style="text-align:left;">
AFINN
</td>
<td style="text-align:left;">
A lexicon used for measuring psychological valence by assigning a level of severity to a term.
</td>
<td style="text-align:left;">
numerical
</td>
<td style="text-align:center;">
-5,-4,-3,-2,-1,0,1,2,3,4,5
</td>
<td style="text-align:left;">
<a href="https://github.com/fnielsen/afinn" target="_blank">AFINN</a>
</td>
</tr>
</tbody>
</table>
<p>We can categorize the lyrics and then perform some text based transformations and manipulations to construct some visualizations.</p>
<p>Using the <code>tidy_lyrics_nsw</code> data set that we created earlier, we will filter out any numbers in our data set and</p>
<ol style="list-style-type: decimal">
<li><p>Get the <strong>Bing</strong> lexicon with the get_sentiments() function.</p></li>
<li><p>Join the <strong>Bing</strong> lexicon to the tokenized data set, specify by = “word”</p></li>
</ol>
<pre class="r"><code>emotions_lyrics_bing &lt;- tidy_lyrics_nsw %&gt;% 
  filter(!grepl(&#39;[0-9]&#39;, word)) %&gt;% 
  left_join(get_sentiments(&quot;bing&quot;), by = &quot;word&quot;) %&gt;% 
  group_by(album) %&gt;%   
  mutate(sentiment = ifelse(is.na(sentiment), &#39;neutral&#39;, sentiment))

emotions_lyrics_bing</code></pre>
<pre><code>## # A tibble: 1,605 x 6
## # Groups:   album [2]
##    album                 track_title track_n  line word    sentiment
##    &lt;chr&gt;                 &lt;chr&gt;         &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    
##  1 ***American Beauty*** Box of Rain       1     1 window  neutral  
##  2 ***American Beauty*** Box of Rain       1     2 morning neutral  
##  3 ***American Beauty*** Box of Rain       1     2 day     neutral  
##  4 ***American Beauty*** Box of Rain       1     3 sun     neutral  
##  5 ***American Beauty*** Box of Rain       1     3 shine   positive 
##  6 ***American Beauty*** Box of Rain       1     4 bird    neutral  
##  7 ***American Beauty*** Box of Rain       1     4 wing    neutral  
##  8 ***American Beauty*** Box of Rain       1     4 rain    neutral  
##  9 ***American Beauty*** Box of Rain       1     4 fall    negative 
## 10 ***American Beauty*** Box of Rain       1     4 heavy   neutral  
## # … with 1,595 more rows</code></pre>
<p>Again, there is a lot going on here! Let’s break it down line by line:</p>
<ol style="list-style-type: decimal">
<li><p>The <code>tidy_lyrics_nsw</code> data set has been called. We are using this rather than <code>tidy_lyrics</code> because the stop words were removed.</p></li>
<li><p>We use <code>filter(!grepl('[0-9]', word))</code> to filter out any numbers in our data set, namely in the <code>word</code> column.</p></li>
<li><p>To get the <strong>Bing</strong> lexicon and compare it to our list of words, we use <code>left_join(get_sentiments("bing"), by = "word")</code>.</p></li>
<li><p>Like before, we used <code>group_by(album)</code> to perform all operations by album (or within each album if you prefer).</p></li>
<li><p>To perform most any operation on a data set when using <code>%&gt;%</code>, we use <code>mutate</code>. In this case, we are using a logic statement to tell the program if it sees an entry with <code>NA</code> in the sentiment column, change it to the term <code>neutral</code>.</p></li>
</ol>
<p>For a total count, we delineate the sentiments and count how many are in each by album using <code>count(sentiment)</code> which uses the <code>sentiment</code> column.</p>
<pre class="r"><code>emotions_lyrics_bing %&gt;%
  count(sentiment)</code></pre>
<pre><code>## # A tibble: 6 x 3
## # Groups:   album [2]
##   album                  sentiment     n
##   &lt;chr&gt;                  &lt;chr&gt;     &lt;int&gt;
## 1 ***American Beauty***  negative     62
## 2 ***American Beauty***  neutral     703
## 3 ***American Beauty***  positive     62
## 4 ***Shakedown Street*** negative     76
## 5 ***Shakedown Street*** neutral     619
## 6 ***Shakedown Street*** positive     83</code></pre>
<div id="basic-text-analysis" class="section level2">
<h2>Basic Text Analysis</h2>
<div id="most-common-positive-and-negative-words-in-a-bar-graph" class="section level3">
<h3>Most Common Positive and Negative Words in a Bar Graph</h3>
<p>We can associate terms tagged with a negative sentiment with negative numbers to better visualize them. To accomplish this, we can create a logic statement called an if-else statement that assigns -n to a word with a negative sentiment and to everything else, it provides an n count. We’ll then order the words in these groups by the number of times they appear in the plot.</p>
<pre class="r"><code>word_count &lt;- emotions_lyrics_bing %&gt;% 
  count(word, sentiment, sort = TRUE) 

word_count</code></pre>
<pre><code>## # A tibble: 693 x 4
## # Groups:   album [2]
##    album                  word     sentiment     n
##    &lt;chr&gt;                  &lt;chr&gt;    &lt;chr&gt;     &lt;int&gt;
##  1 ***Shakedown Street*** love     positive     45
##  2 ***Shakedown Street*** lovin    neutral      25
##  3 ***Shakedown Street*** fire     neutral      24
##  4 ***Shakedown Street*** doctor   neutral      17
##  5 ***American Beauty***  home     neutral      16
##  6 ***Shakedown Street*** stagger  neutral      16
##  7 ***American Beauty***  friend   neutral      14
##  8 ***American Beauty***  time     neutral      14
##  9 ***Shakedown Street*** lee      neutral      14
## 10 ***Shakedown Street*** mountain neutral      14
## # … with 683 more rows</code></pre>
<p>In the above, we are going to</p>
<ol style="list-style-type: decimal">
<li><p>Use the <code>emotions_lyrics_bing</code> data set.</p></li>
<li><p>Count up the words by sentiment and then sort them by <code>count(word, sentiment, sort = TRUE)</code></p></li>
</ol>
<pre class="r"><code>top_sentiments_bing &lt;-  word_count %&gt;% 
  filter(sentiment != &#39;neutral&#39;) %&gt;% 
  group_by(sentiment) %&gt;% 
  top_n(10, n) %&gt;% 
  mutate(num = ifelse(sentiment == &quot;negative&quot;, -n, n)) %&gt;%  
  select(-n) %&gt;% 
  mutate(word = reorder(word, num)) %&gt;% 
  ungroup() 

top_sentiments_bing</code></pre>
<pre><code>## # A tibble: 21 x 4
##    album                  word    sentiment   num
##    &lt;chr&gt;                  &lt;fct&gt;   &lt;chr&gt;     &lt;int&gt;
##  1 ***Shakedown Street*** love    positive     45
##  2 ***American Beauty***  easy    positive     13
##  3 ***American Beauty***  sweet   positive      9
##  4 ***American Beauty***  devil   negative     -7
##  5 ***Shakedown Street*** dark    negative     -6
##  6 ***American Beauty***  fall    negative     -5
##  7 ***American Beauty***  lie     negative     -5
##  8 ***American Beauty***  numb    negative     -5
##  9 ***Shakedown Street*** dead    negative     -5
## 10 ***Shakedown Street*** miracle positive      5
## # … with 11 more rows</code></pre>
<p>Let’s break it down line by line:</p>
<ol style="list-style-type: decimal">
<li><p>The <code>word_count</code> data set has been called.</p></li>
<li><p>We use <code>filter(sentiment != 'neutral')</code> to filter out any term in the <code>sentiment</code> column that is <code>neutral</code>.</p></li>
<li><p>To get the top 10 of words used in each album use <code>top_n(10, n)</code>.</p></li>
<li><p>We use a logic statement <code>mutate(num = ifelse(sentiment == "negative", -n, n))</code> to tell R that if it sees the term <code>neutral</code> in the sentiment column, to change the the count associated with it to a negative in a new column called <code>num</code>.</p></li>
<li><p>Using <code>select(-n)</code> tells the program that we want to get rid of the the column <code>n</code>. You can think of the negative as a way to deselect a column.</p></li>
<li><p>We simply put the terms from greatest to least disregarding album by <code>mutate(word = reorder(word, num))</code>.</p></li>
</ol>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/top_sentiments_plot_true-1.png" width="672" /></p>
<pre class="r"><code>ggplot(top_sentiments_bing, aes(reorder(word, num), num, fill = sentiment)) +
  geom_bar(stat = &#39;identity&#39;, alpha = 0.75) + 
  scale_fill_manual(guide = FALSE, values = c(&quot;#d9534f&quot;, &quot;#428bca&quot;)) +
  scale_y_continuous(limits = c(-10, 55), breaks = pretty_breaks(7)) + 
  labs(x = &#39;&#39;, y = &quot;Number of Occurrences&quot;,
       title = &#39;Top Sentiments of Lyrics&#39;,
       subtitle = &#39;Most Common Positive and Negative Words&#39;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14 , face = &quot;bold&quot;),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size = 1.1),
        panel.spacing = unit(0.5, &quot;cm&quot;)) +
   facet_wrap(album ~ ., scales = &quot;free_x&quot;)</code></pre>
<p>Now there a bunch of things going on in this bar plot too!</p>
<ol style="list-style-type: decimal">
<li><p>Here we are using the <code>top_sentiments_bing</code> data set but reordering the way its plotted by greatest to least and filling by positive or negative sentiment by <code>aes(reorder(word, num), num, fill = sentiment)</code>.</p></li>
<li><p><code>geom_bar</code> is a bar graph as we saw before, but here the transparency level is set to 75% by <code>alpha = 0.75</code>.</p></li>
<li><p>The positive and negative colors are set to a specific blue (#d9534f) and red (#428bca), respectively by <code>scale_fill_manual(guide = FALSE, values = c("#d9534f", "#428bca"))</code>. Additionally, the legend has been turned off as well.</p></li>
<li><p>The y-axis is limited to plotting between -10 and 55 with an even number of breaks given by <code>scale_y_continuous(limits = c(-10, 55), breaks = pretty_breaks(7))</code>.</p></li>
<li><p><code>labs</code> provides the opportunity to name the axes, title and subtitle.</p></li>
<li><p>One of the default themes that can be used by <code>ggplot</code> is <code>theme_bw()</code> or a black and white theme.</p></li>
<li><p>The values along the x-axis can be aesthetically manipulated to be at a 45 degree angle in size 14 bold print right-adjusted by <code>axis.text.x = element_text(angle = 45, hjust = 1, size = 14, face = "bold")</code>.</p></li>
</ol>
</div>
<div id="most-common-positive-and-negative-words-in-a-wordcloud" class="section level3">
<h3>Most Common Positive and Negative Words in a WordCloud</h3>
<p>To compare the words within each album, we can initially use a comparison wordcloud. Now we can create this using <code>ggwordcloud</code> as before, but if you just want a quick look, an older package named <code>wordcloud</code> does a pretty good job and it has a built in function for comparisons.</p>
<p>Let’s take a look at the album <strong><em>American Beauty</em></strong> first:</p>
<pre class="r"><code>emotions_lyrics_bing %&gt;%
  filter(album == &quot;***American Beauty***&quot;) %&gt;%
  filter(sentiment != &quot;neutral&quot;) %&gt;% 
  count(word, sentiment, sort = TRUE) %&gt;% 
  spread(sentiment, n, fill = 0L) %&gt;% 
  as.data.frame() %&gt;% 
  remove_rownames() %&gt;% 
  column_to_rownames(&quot;word&quot;) %&gt;% 
  select(-album) %&gt;%
  comparison.cloud(colors = c(&quot;#d9534f&quot;, &quot;#428bca&quot;), title.size = 1.5)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/am_beauty_cwc-1.png" width="672" /></p>
<p>and then <strong><em>Shakedown Street</em></strong>:</p>
<pre class="r"><code>emotions_lyrics_bing %&gt;%
  filter(album == &quot;***Shakedown Street***&quot;) %&gt;%
  filter(sentiment != &quot;neutral&quot;) %&gt;% 
  count(word, sentiment, sort = TRUE) %&gt;% 
  spread(sentiment, n, fill = 0L) %&gt;% 
  as.data.frame() %&gt;% 
  remove_rownames() %&gt;% 
  column_to_rownames(&quot;word&quot;) %&gt;% 
  select(-album) %&gt;%
  comparison.cloud(colors = c(&quot;#d9534f&quot;, &quot;#428bca&quot;), title.size = 1.5)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/shakedown_st_cwc-1.png" width="672" /></p>
<p>Without being repetitive, the only command you haven’t seen is <code>spread</code> which essentially takes a long data set and converts it into a wide one. Both <code>spread</code> and its counterpart <code>gather</code> are commands that are used often and worth your time getting to know a bit about, though the current incarnations of these known as <code>pivot_wider</code> and <code>pivot_longer</code>. If interested, take a look at the online version of the text <a href="https://r4ds.had.co.nz/tidy-data.html?q=pivot#pivoting" target="_blank">R for Data Science</a>.</p>
</div>
<div id="positive-and-negative-words-in-a-line-graph" class="section level3">
<h3>Positive and Negative Words in a Line Graph</h3>
<p>Now that we’ve looked at the most common words for either positive or negative sentiment, what proportion of these sentiments are present in within the entire lyrical data set?</p>
<pre class="r"><code>pos_neg_bing_album &lt;- tidy_lyrics_nsw %&gt;% 
  filter(!grepl(&#39;[0-9]&#39;, word)) %&gt;% 
  left_join(get_sentiments(&quot;bing&quot;), by = &quot;word&quot;) %&gt;% 
  mutate(sentiment = ifelse(is.na(sentiment), &#39;neutral&#39;, sentiment)) %&gt;%   
  group_by(album, sentiment) %&gt;% 
  summarize(n = n()) %&gt;% 
  mutate(percent = n / sum(n)) %&gt;% 
  select(-n) %&gt;% 
  ungroup() </code></pre>
<pre><code>## `summarise()` regrouping output by &#39;album&#39; (override with `.groups` argument)</code></pre>
<pre class="r"><code>pos_neg_bing_album</code></pre>
<pre><code>## # A tibble: 6 x 3
##   album                  sentiment percent
##   &lt;chr&gt;                  &lt;chr&gt;       &lt;dbl&gt;
## 1 ***American Beauty***  negative   0.0750
## 2 ***American Beauty***  neutral    0.850 
## 3 ***American Beauty***  positive   0.0750
## 4 ***Shakedown Street*** negative   0.0977
## 5 ***Shakedown Street*** neutral    0.796 
## 6 ***Shakedown Street*** positive   0.107</code></pre>
<pre class="r"><code>pos_neg_bing_album %&gt;% 
  filter(sentiment != &quot;neutral&quot;) %&gt;% 
  ggplot(aes(x = album, y = percent, color = sentiment, group = sentiment)) + 
  geom_line(size = 1) + 
  geom_point(size = 3) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  labs(x = &quot;Album&quot;, y = &quot;Emotion Words Count (as %)&quot;) +
  scale_color_manual(values = c(positive = &quot;#d9534f&quot;, negative = &quot;#428bca&quot;)) +
  ggtitle(&quot;Proportion of Positive and Negative Words by Album&quot;, 
          subtitle = &quot;Bing lexicon&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = &quot;bold&quot;),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 11, face = &quot;bold&quot;))</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/albums_pos_neg_plot-1.png" width="672" /></p>
<p>Well while this isn’t overtly interesting, it does provide some indication that while <strong><em>Shakedown Street</em></strong> is slightly more positive, it is also more negative as well. Maybe we’ll get a better idea by looking at the individual songs:</p>
<pre class="r"><code>pos_neg_bing_track &lt;- tidy_lyrics_nsw %&gt;% 
  filter(!grepl(&#39;[0-9]&#39;, word)) %&gt;% 
  left_join(get_sentiments(&quot;bing&quot;), by = &quot;word&quot;) %&gt;% 
  mutate(sentiment = ifelse(is.na(sentiment), &#39;neutral&#39;, sentiment)) %&gt;%   
  group_by(album, track_title, track_n, sentiment) %&gt;% 
  summarize(n = n()) %&gt;% 
  mutate(percent = n / sum(n)) %&gt;% 
  select(-n) </code></pre>
<pre><code>## `summarise()` regrouping output by &#39;album&#39;, &#39;track_title&#39;, &#39;track_n&#39; (override with `.groups` argument)</code></pre>
<pre class="r"><code>pos_neg_bing_track</code></pre>
<pre><code>## # A tibble: 64 x 5
## # Groups:   album, track_title, track_n [22]
##    album                 track_title       track_n sentiment percent
##    &lt;chr&gt;                 &lt;chr&gt;               &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;
##  1 ***American Beauty*** Attics of My Life       9 negative   0.04  
##  2 ***American Beauty*** Attics of My Life       9 neutral    0.92  
##  3 ***American Beauty*** Attics of My Life       9 positive   0.04  
##  4 ***American Beauty*** Box of Rain             1 negative   0.0741
##  5 ***American Beauty*** Box of Rain             1 neutral    0.889 
##  6 ***American Beauty*** Box of Rain             1 positive   0.0370
##  7 ***American Beauty*** Brokedown Palace        7 negative   0.0392
##  8 ***American Beauty*** Brokedown Palace        7 neutral    0.892 
##  9 ***American Beauty*** Brokedown Palace        7 positive   0.0686
## 10 ***American Beauty*** Candyman                5 negative   0.0615
## # … with 54 more rows</code></pre>
<pre class="r"><code>pos_neg_bing_track %&gt;% 
  filter(sentiment != &quot;neutral&quot;) %&gt;% 
  ggplot(aes(x = reorder(track_title, track_n), y = percent, color = sentiment, 
             group = sentiment)) + 
  geom_line(size = 1) + 
  geom_point(size = 3) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  labs(x = &quot;Album&quot;, y = &quot;Sentiment Count (as %)&quot;) +
  scale_color_manual(values = c(positive = &quot;#d9534f&quot;, negative = &quot;#428bca&quot;)) +
  ggtitle(&quot;Proportion of Positive and Negative Words by Track&quot;, 
          subtitle = &quot;Bing lexicon&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = &quot;bold&quot;),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 11, face = &quot;bold&quot;)) +
  facet_wrap(. ~ album, ncol = 1, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/track_pos_neg_plot-1.png" width="1152" /></p>
<p>Firstly, you may notice that <code>geom_line</code>, <code>geom_point</code>, and <code>reorder(track_title, track_n)</code>. The first two are fairly obvious as they are parts of the visualization that render the dots and lines. In the latter, we arrange the tracks by their original order since many artists tend to itemize tracks in a preferred way. Sometimes this is intended to tell a story<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> while other times it is simply a personal or studio preference.</p>
<p>Visually, the ebbs and flows of the sentiments within each album are relatively consistent and are reflections of each other as one would expect. In fact they both have an instance where the sentiments have a declining slop. The primary differential is the area between the positive and negative curves which is greater in the album <strong><em>Shakedown Street</em></strong> than <strong><em>American Beauty</em></strong>. In fact, it is this disparity that is the main contribution to the earlier variant of this plot which looked at the albums as a whole.</p>
</div>
<div id="positive-and-negative-words-in-a-boxplot" class="section level3">
<h3>Positive and Negative Words in a Boxplot</h3>
<p>No we switch our attention to something that may be of greater interest, that is the <code>NRC</code> lexicon. Recall this dictionary not only has positive and negative categories, it also has eight different emotional classifications: <em>Anger</em>, <em>Anticipation</em>, <em>Disgust</em>, <em>Fear</em>, <em>Joy</em>, <em>Sadness</em>, <em>Surprise</em>, and <em>Trust</em>.</p>
<p>In this case we will disregard the positive and negative tags but please note that what <code>Bing</code> classifies by either tag may not necessarily be the same as how <strong>NRC</strong> groups them. In a nutshell, both <code>Bing</code> and <code>NRC</code> are different lexicons from two different sources so it would make sense that there would be a discrepancy between classifications.</p>
<p>Using a similar approach as before, we first look at the differentials by album:</p>
<pre class="r"><code>emotions_album_nrc &lt;- tidy_lyrics_nsw  %&gt;% 
  left_join(get_sentiments(&quot;nrc&quot;), by = &quot;word&quot;) %&gt;% 
  filter(!(sentiment == &quot;negative&quot; | sentiment == &quot;positive&quot;)) %&gt;% 
  mutate(sentiment = as.factor(sentiment)) %&gt;% 
    group_by(album, sentiment) %&gt;%
  summarize(n = n()) %&gt;% 
  mutate(percent = n / sum(n)) %&gt;%   
  select(-n) %&gt;% 
  ungroup() </code></pre>
<pre><code>## `summarise()` regrouping output by &#39;album&#39; (override with `.groups` argument)</code></pre>
<pre class="r"><code>emotions_album_nrc </code></pre>
<pre><code>## # A tibble: 16 x 3
##    album                  sentiment    percent
##    &lt;chr&gt;                  &lt;fct&gt;          &lt;dbl&gt;
##  1 ***American Beauty***  anger         0.0611
##  2 ***American Beauty***  anticipation  0.195 
##  3 ***American Beauty***  disgust       0.0611
##  4 ***American Beauty***  fear          0.0656
##  5 ***American Beauty***  joy           0.208 
##  6 ***American Beauty***  sadness       0.143 
##  7 ***American Beauty***  surprise      0.0905
##  8 ***American Beauty***  trust         0.176 
##  9 ***Shakedown Street*** anger         0.0892
## 10 ***Shakedown Street*** anticipation  0.140 
## 11 ***Shakedown Street*** disgust       0.0255
## 12 ***Shakedown Street*** fear          0.178 
## 13 ***Shakedown Street*** joy           0.219 
## 14 ***Shakedown Street*** sadness       0.110 
## 15 ***Shakedown Street*** surprise      0.104 
## 16 ***Shakedown Street*** trust         0.134</code></pre>
<p>and then the corresponding plot.</p>
<pre class="r"><code>emotions_album_nrc %&gt;% 
  ggplot() +
  geom_boxplot(aes(x = reorder(sentiment, percent), y = percent, fill = sentiment)) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  scale_fill_brewer(palette = &quot;Spectral&quot;) +
  ggtitle(&quot;Distribution of Sentiments by Album&quot;) +
  labs(x = &quot;Sentiment&quot;, y = &quot;Percentage&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        legend.position = &quot;none&quot;,
        axis.text.x = element_text(size = 11, face = &quot;bold&quot;),
        axis.text.y = element_text(size = 11, face = &quot;bold&quot;)) +
  facet_wrap(. ~ album, ncol = 1, scales = &quot;free&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/album_nrc_plot-1.png" width="1152" /></p>
<p>The lack of boxes isn’t surprising considering we only have one value for each sentiment per album. What is interesting is that the percent of terms associated with anger, anticipation, fear and trust are elevated in <strong><em>Shakedown Street</em></strong>.</p>
<p>Now a bit of social commentary: These emotions tend to reflect the inner turmoil going on within the band where two of the staple members (Keith and Donna Jean Godchaux) left the band after it was reportedly found that Donna Jean was having an affair with another band member by the name of Bob Weir. Let’s see if this is reflected in the songs themselves.</p>
<pre class="r"><code>emotions_tracks_nrc &lt;- tidy_lyrics_nsw  %&gt;% 
  left_join(get_sentiments(&quot;nrc&quot;), by = &quot;word&quot;) %&gt;% 
  filter(!(sentiment == &quot;negative&quot; | sentiment == &quot;positive&quot;)) %&gt;% 
  mutate(sentiment = as.factor(sentiment)) %&gt;% 
  group_by(album, track_title, track_n, sentiment) %&gt;% 
  summarize(n = n()) %&gt;% 
  mutate(percent = n / sum(n)) %&gt;%   
  select(-n) %&gt;% 
  ungroup() </code></pre>
<pre><code>## `summarise()` regrouping output by &#39;album&#39;, &#39;track_title&#39;, &#39;track_n&#39; (override with `.groups` argument)</code></pre>
<pre class="r"><code>emotions_tracks_nrc </code></pre>
<pre><code>## # A tibble: 149 x 5
##    album                 track_title       track_n sentiment    percent
##    &lt;chr&gt;                 &lt;chr&gt;               &lt;int&gt; &lt;fct&gt;          &lt;dbl&gt;
##  1 ***American Beauty*** Attics of My Life       9 anger         0.0625
##  2 ***American Beauty*** Attics of My Life       9 anticipation  0.25  
##  3 ***American Beauty*** Attics of My Life       9 disgust       0.0625
##  4 ***American Beauty*** Attics of My Life       9 joy           0.125 
##  5 ***American Beauty*** Attics of My Life       9 sadness       0.188 
##  6 ***American Beauty*** Attics of My Life       9 surprise      0.0625
##  7 ***American Beauty*** Attics of My Life       9 trust         0.25  
##  8 ***American Beauty*** Box of Rain             1 anger         0.0345
##  9 ***American Beauty*** Box of Rain             1 anticipation  0.276 
## 10 ***American Beauty*** Box of Rain             1 fear          0.103 
## # … with 139 more rows</code></pre>
<p>and then the corresponding plot.</p>
<pre class="r"><code>emotions_tracks_nrc  %&gt;% 
  ggplot() +
  geom_boxplot(aes(x = reorder(sentiment, percent), y = percent, fill = sentiment)) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  scale_fill_brewer(palette = &quot;Spectral&quot;) +
  ggtitle(&quot;Distribution of Sentiments by Album Aggregated by Track&quot;) +
  labs(x = &quot;Detected Sentiments&quot;, y = &quot;Percentage&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        legend.position = &quot;none&quot;,
        axis.text.x = element_text(size = 11, face = &quot;bold&quot;),
        axis.text.y = element_text(size = 11, face = &quot;bold&quot;)) +
  facet_wrap(. ~ album, ncol = 1, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/tracks_nrc_plot-1.png" width="672" /></p>
<p>So when we look at the scores by track and then aggregate, we see the the original findings seem to be correct though there is great deal more variability in joy within <strong><em>Shakedown Street</em></strong> that wasn’t detected earlier (maybe it was the disco). Additionally there appears to be a greater association with sadness in <strong><em>American Beauty</em></strong> that was not found earlier as well. While you may not be familiar with the album, the new findings here are also not a bug surprise. The album is known for its polar track sequencing where an extremely upbeat song (reflected in joy) would be followed by one that is sorrowful (reflected almost equally by sadness).</p>
<p>What if we wanted to see how the songs changed by track order? We can use a bump chart to visualize this</p>
<pre class="r"><code>emotions_tracks_nrc %&gt;% 
  ggplot(aes(reorder(track_title, track_n), percent, color = sentiment, 
             group = sentiment)) +
  geom_line(size = 1.5) +
  geom_point(size = 3.5) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  xlab(&quot;Album&quot;) + ylab(&quot;Proportion of Sentiments&quot;) +
  ggtitle(&quot;Sentiments by Albums&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = &quot;bold&quot;),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 11, face = &quot;bold&quot;)) +
  scale_color_brewer(palette = &quot;Spectral&quot;) +
  facet_wrap(. ~ album, ncol = 1, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/tracks_agg_nrc_bump-1.png" width="1152" /></p>
<p>Well that got messy. Even with the colors, it is hard to discern what is going on. This is a good instance where you can use <code>facet_grid</code>. Until now, we have been using <code>facet_wrap</code> to separate the <code>album</code> variable into its distinct entries. However the functionality of <code>facet_wrap</code> is limited and will return a symmetrical matrix of plots for the number of unique levels or factors of a given variable. <code>facet_grid</code> serves another purpose by return facets equal to the levels or factors of a given variable. Think of it more this way -</p>
<ul>
<li><p><code>facet_wrap</code> essentially splits your plot across the categories you want.</p></li>
<li><p><code>facet_grid</code> does a similar thing but instead of creating different plots it creates different grids and then plots each plot in the grids.</p></li>
</ul>
<p>Still confused? Well let’s apply it and see.</p>
<pre class="r"><code>emotions_tracks_nrc %&gt;% 
  ggplot(aes(x = reorder(track_title, track_n), y = percent, color = sentiment, 
             group = sentiment)) +
  geom_line(size = 1.5) +
  geom_point(size = 3.5) +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  xlab(&quot;Album&quot;) + ylab(&quot;Proportion of Sentiments&quot;) +
  ggtitle(&quot;Individual Sentiments by Album&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = &quot;bold&quot;),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 8, face = &quot;bold&quot;)) +
  scale_color_brewer(palette = &quot;Spectral&quot;) +
  facet_grid(sentiment ~ album, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/tracks_ind_nrc_bump-1.png" width="1152" /></p>
<p>We only changed <code>facet_wrap(. ~ album, ncol = 1, scales = "free_x")</code> in the messy plot to <code>facet_grid(sentiment ~ album, scales = "free_x")</code> in the new one. Sure it could still use some work on the aesthetics side of things but the line graphs are now provided by type, or facet which makes a visual comparison much easier.</p>
<p>With a few exceptions, you may notice that the sentiments share a common shape when comparing tracks in order. This consistency is not an outlier. One of the reasons you may enjoy a follow-up album by an artist you liked before is hypothesized to having a similar line of best fit. Don’t believe me? Try it yourself and hopefully you remember some basic terms from Algebra.</p>
<p>First let’s define a binomial function</p>
<pre class="r"><code>binomial_smooth &lt;- function(...) {
  geom_smooth(method = &quot;glm&quot;, method.args = list(family = &quot;binomial&quot;), ...)
}</code></pre>
<p>and then apply it as a third degree polynomial</p>
<pre class="r"><code>emotions_tracks_nrc %&gt;% 
  ggplot(aes(x = reorder(track_title, track_n), y = percent, color = sentiment, 
             group = sentiment)) +
  geom_line(size = 1.5) +
  geom_point(size = 3.5) +
  binomial_smooth(formula = y ~ splines::ns(x, 3), color = &quot;#000000&quot;)   +
  scale_y_continuous(breaks = pretty_breaks(5), labels = percent_format()) +
  xlab(&quot;Album&quot;) + ylab(&quot;Proportion of Sentiments&quot;) +
  ggtitle(&quot;Individual Sentiments by Album&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = &quot;bold&quot;),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 8, face = &quot;bold&quot;)) +
  scale_color_brewer(palette = &quot;Spectral&quot;) +
  facet_grid(sentiment ~ album, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/tracks_ind_nrc_bump_glm-1.png" width="1152" /></p>
<p>Change the number <code>3</code> in <code>binomial_smooth(formula = y ~ splines::ns(x, 3), color = "#000000")</code> to amend the degree as you see fit. In any case, you may notice that the line of best fit is relatively consistent between the two albums when assessing sentiments in track order.</p>
</div>
</div>
<div id="viewing-across-all-lexicons" class="section level2">
<h2>Viewing Across all Lexicons</h2>
<p>Let’s compare the lexicons themselves on how many positive and negative words they each categorize.</p>
<pre class="r"><code>get_sentiments(&quot;bing&quot;) %&gt;% 
  count(sentiment)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sentiment     n
##   &lt;chr&gt;     &lt;int&gt;
## 1 negative   4781
## 2 positive   2005</code></pre>
<pre class="r"><code>get_sentiments(&quot;nrc&quot;) %&gt;% 
  count(sentiment)</code></pre>
<pre><code>## # A tibble: 10 x 2
##    sentiment        n
##    &lt;chr&gt;        &lt;int&gt;
##  1 anger         1247
##  2 anticipation   839
##  3 disgust       1058
##  4 fear          1476
##  5 joy            689
##  6 negative      3324
##  7 positive      2312
##  8 sadness       1191
##  9 surprise       534
## 10 trust         1231</code></pre>
<ul>
<li><p>In the <code>bing</code> lexicon, there are 4781 negative and 2005 positive terms.</p></li>
<li><p>In the <code>nrc</code> lexicon, there are 3324 negative and 2312 positive terms.</p></li>
</ul>
<pre class="r"><code>get_sentiments(&quot;afinn&quot;) %&gt;% 
  count(value)</code></pre>
<pre><code>## # A tibble: 11 x 2
##    value     n
##    &lt;dbl&gt; &lt;int&gt;
##  1    -5    16
##  2    -4    43
##  3    -3   264
##  4    -2   966
##  5    -1   309
##  6     0     1
##  7     1   208
##  8     2   448
##  9     3   172
## 10     4    45
## 11     5     5</code></pre>
<ul>
<li>In the <code>AFINN</code> lexicon, the measure with regards to the severity of a term being positive or negative, rather than just treating a word as one or the other. However, we can just treat the negative measures as negative sentiments and the positive measures as positive sentiments just to get a general idea of the total number. With that in mind, we can do the following:</li>
</ul>
<pre class="r"><code>get_sentiments(&quot;afinn&quot;) %&gt;% 
  select(value) %&gt;% 
  mutate(sentiment = if_else(value &gt; 0, &quot;positive&quot;, &quot;negative&quot;, &quot;NA&quot;)) %&gt;% 
  group_by(sentiment) %&gt;% 
  summarize(sum = n()) %&gt;%
  filter(sentiment == &quot;positive&quot; | sentiment == &quot;negative&quot;)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sentiment   sum
##   &lt;chr&gt;     &lt;int&gt;
## 1 negative   1599
## 2 positive    878</code></pre>
<ul>
<li>In the <code>AFINN</code> lexicon, there are (generally) 1599 negative and 877 positive terms.</li>
</ul>
<p>Now taking a look at our data set, let’s see how our terms get tagged.</p>
<pre class="r"><code>emotions_lyrics_bing %&gt;% 
  group_by(sentiment) %&gt;% 
  summarize(sum = n()) %&gt;%  
  filter(sentiment == &quot;positive&quot; | sentiment == &quot;negative&quot;)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sentiment   sum
##   &lt;chr&gt;     &lt;int&gt;
## 1 negative    138
## 2 positive    145</code></pre>
<p><code>bing</code> tags 134 of our terms as negative and 143 as positive.</p>
<pre class="r"><code>tidy_lyrics_nsw %&gt;%
  left_join(get_sentiments(&quot;nrc&quot;), by = &quot;word&quot;) %&gt;% 
  group_by(sentiment) %&gt;% 
  summarize(sum = n()) %&gt;%
  filter(sentiment == &quot;positive&quot; | sentiment == &quot;negative&quot;)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sentiment   sum
##   &lt;chr&gt;     &lt;int&gt;
## 1 negative    145
## 2 positive    264</code></pre>
<p>However, <code>nrc</code> tags 140 of our terms as negative and 258 as positive.</p>
<pre class="r"><code>emotions_lyrics_afinn &lt;- tidy_lyrics_nsw  %&gt;% 
  left_join(get_sentiments(&quot;afinn&quot;), by = &quot;word&quot;) %&gt;% 
  filter(!grepl(&#39;[0-9]&#39;, word))

emotions_lyrics_afinn %&gt;% 
  select(value) %&gt;% 
  mutate(sentiment = if_else(value &gt; 0, &quot;positive&quot;, &quot;negative&quot;, &quot;NA&quot;)) %&gt;% 
  group_by(sentiment) %&gt;% 
  summarize(sum = n()) %&gt;%
  filter(sentiment == &quot;positive&quot; | sentiment == &quot;negative&quot;)</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   sentiment   sum
##   &lt;chr&gt;     &lt;int&gt;
## 1 negative    116
## 2 positive    155</code></pre>
<p>Finally <code>AFINN</code> (generally) tags 113 of our terms as negative and 153 as positive.</p>
<p>So you can see that the sentiments are dependent on lexicons. Is this a bad thing? Well it depends on what you are using it for.</p>
<p>Now let’s put all of the lexicons together and see how they compare. Note that there is a lot below which will not have a line-by-line explanation. At this point, try reading the code to figure out what is occurring. You may find this to be easier when using albums of artists that you enjoy. In any case, please ask questions if needed!</p>
<div style="page-break-after: always;"></div>
<p>First we calculate <strong>AFINN</strong> sentiment scores and compare them to the list of terms we already have.</p>
<pre class="r"><code>afinn_scores &lt;- emotions_lyrics_afinn %&gt;% 
  replace_na(replace = list(value = 0)) %&gt;%
  group_by(index = album, track_title) %&gt;% 
  summarize(sentiment = sum(value)) %&gt;% 
  mutate(lexicon = &quot;AFINN&quot;)</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;index&#39; (override with `.groups` argument)</code></pre>
<p>We then combine both the <code>bing</code> and <code>nrc</code> lexicons into one data frame and calculate the sentiment scores for each.</p>
<pre class="r"><code>bing_nrc_scores &lt;- bind_rows(
  tidy_lyrics_nsw %&gt;% 
    inner_join(get_sentiments(&quot;bing&quot;)) %&gt;% 
    mutate(lexicon = &quot;Bing&quot;),
  tidy_lyrics %&gt;% 
    inner_join(get_sentiments(&quot;nrc&quot;) %&gt;% 
                 filter(sentiment %in% c(&quot;positive&quot;, &quot;negative&quot;))) %&gt;% 
    mutate(lexicon = &quot;NRC&quot;)) %&gt;% 
  # from here we count the sentiments, spread on positive/negative, 
  # then create the final sentiment score:
  count(lexicon, index = album, track_title, sentiment) %&gt;% 
  spread(sentiment, n, fill = 0) %&gt;% 
  mutate(lexicon = as.factor(lexicon),
         sentiment = positive - negative)</code></pre>
<pre><code>## Joining, by = &quot;word&quot;
## Joining, by = &quot;word&quot;</code></pre>
<p>Finally we compile a list of all three lexicons using the <code>bind_rows</code> command.</p>
<pre class="r"><code>all_lexicons &lt;- bind_rows(afinn_scores, bing_nrc_scores) %&gt;%
  select(-negative, -positive)</code></pre>
<p>Try <code>View(all_lexicons)</code> if you want to view the resulting data frame. To make the final plot more interesting, let’s assign a palette using hex colors.</p>
<pre class="r"><code>lexicon_cols &lt;- c(&quot;AFINN&quot; = &quot;#ae5a41&quot;, &quot;NRC&quot; = &quot;#559e83&quot;, &quot;Bing&quot; = &quot;#1b85b8&quot;)</code></pre>
<p>Finally we plot all of the lexicons by album and score.</p>
<pre class="r"><code>all_lexicons %&gt;% 
  ggplot(aes(track_title, sentiment, fill = lexicon)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~lexicon, ncol = 1, scales = &quot;free_y&quot;) +
  scale_fill_manual(values = lexicon_cols) +
  ggtitle(&quot;Comparison of Sentiments&quot;, subtitle = &quot;by track order&quot;) +
  labs(x = &quot;Index of All Songs&quot;, y = &quot;Sentiment Score&quot;) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5),
        axis.text.x = element_blank()) +
  facet_grid(lexicon ~ index, scales = &quot;free_x&quot;)</code></pre>
<p><img src="/lesson/SentimentAnalysisIntro_files/figure-html/all_lexicons_plot-1.png" width="672" /></p>
<p>Well that is a lot to take in but this is essentially one way statistics can be applied! We have taken open text, broken it down into its basic terms, filtered out common terms, and used natural language processing (NLP) including various lexicons to derive sentiments.</p>
<p>This work is registered under the <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/" target="_blank">CC BY-NC-SA 3.0 Creative Commons License</a>. Any items including, but not limited to lyrics, logos, and references associated with the Grateful Dead are licensed under  Grateful Dead Productions unless otherwise noted. All rights reserved.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>like Dark Side of the Moon by Pink Floyd or maybe that reference just dated me and you are even more confused.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

                    </div>

                    



                    
                </div>

                <div class="body-footer">
                    <p>Last updated on January 1, 0001</p>

                    






  
  

<p class="edit-page">
  <a href="https://github.com/piechartssuck/Courses/edp613/edit/edp613/content/lesson/SentimentAnalysisIntro.html">
    <i class="fas fa-pen pr-2"></i>Edit this page
  </a>
</p>




                    

                </div>

            </article>

            <footer>
    <hr>

    <div class="row course-info">
        <div class="col-md-7">
            <p>
                <strong>EDP 613: Statistical Methods I (Fall 2020)</strong><br>

                <a href="https://www.wvu.edu" target="_blank" rel="noopener">West Virginia University</a> &emsp;&emsp;
                <a href="https://lshd.wvu.edu/" target="_blank" rel="noopener">Counseling &amp; Learning Sciences</a>
            </p>

            <p>
                <a href="https://lshd.wvu.edu/faculty-staff/roy" target="_blank" rel="noopener"><i class="fas fa-user fa-fw"></i>
                    Dr. Abhik Roy</a> &emsp;&emsp;
                <a href="mailto:Abhik.Roy@mail.wvu.edu"><i class="fas fa-envelope fa-fw"></i>
                    Abhik.Roy@mail.wvu.edu</a>
            </p>

            <p>
                <i class="far fa-calendar-alt fa-fw"></i> Forever (for the next 13 weeks) &emsp;&emsp;
                <i class="far fa-clock fa-fw"></i> Thursdays from 4:00-6:50 PM
                <br><i class="fas fa-university fa-fw"></i> Agricultural Sciences building Rm. 2004
            </p>
        </div>

        <div class="col-md-5 credits">
            <p>All content licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.</p>

            <p>Content <i class="fab fa-creative-commons fa-fw"></i> 2020 <a href="https://lshd.wvu.edu/faculty-staff/roy" target="_blank" rel="noopener">Abhik Roy</a></p>

            <p>This site was created with the <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> in <a href="https://bookdown.org/yihui/blogdown/" target="_blank" rel="noopener">blogdown</a> and <a href="https://gohugo.io/" target="_blank" rel="noopener">Hugo</a> with customizations heavily influenced by Dr. Andrew Heiss'<a href="https://datavizm20.classes.andrewheiss.com" target="_blank" rel="noopener"> site<a/>. </p>

            <p><a href="https://github.com/piechartssuck/Courses/tree/edp613" target="_blank" rel="noopener"><i class="fab fa-github fa-fw"></i> View the source at GitHub.</a></p>
        </div>
    </div>
</footer>


        </main>
    </div>
</div>

        

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.1/anchor.min.js" integrity="sha256-pB/deHc9CGfFpJRjC43imB29Rse8tak+5eXqntO94ck=" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    

    
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.cbb55fd8eafa574bce72dcb94f65cd2c.js"></script>

    



    
    

    
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>

</html>
